// <auto-generated> by gen_ljidct.py from libjpeg-turbo 3.1 (jidctint.c, jidctred.c, jidctfst.c, jidctflt.c). </auto-generated>
// The inverse DCTs of libjpeg-turbo, one C statement per C# statement: accurate integer 8x8 and scaled 1x1 .. 16x16
// (IDCT scaling), the fast integer 8x8 and the float 8x8. JLONG arithmetic is 32-bit (unchecked) as in the Windows
// builds; P1 is PASS1_BITS (2 for 8-bit, 1 for 12-bit samples); rl / mask are libjpeg's range-limit table and
// RANGE_MASK (IDCT_range_limit for the integer transforms, sample_range_limit for the float one).
#pragma warning disable CS0219, IDE0059, IDE0017
namespace SharpImage.Formats;

public static partial class JpegCoder
{
    private static void LjIdctIslow(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp2, tmp3;
          int tmp10, tmp11, tmp12, tmp13;
          int z1, z2, z3, z4, z5;
          int ctr;
          Span<int> workspace = stackalloc int[64];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 8; ctr > 0; ctr--) {
            if (coef[ip + 8 * 1] == 0 && coef[ip + 8 * 2] == 0 &&
                coef[ip + 8 * 3] == 0 && coef[ip + 8 * 4] == 0 &&
                coef[ip + 8 * 5] == 0 && coef[ip + 8 * 6] == 0 &&
                coef[ip + 8 * 7] == 0) {
              int dcval = ((int)((uint)(((coef[ip + 8 * 0]) * (q[qp + 8 * 0]))) << (P1)));
              workspace[wp + 8 * 0] = dcval;
              workspace[wp + 8 * 1] = dcval;
              workspace[wp + 8 * 2] = dcval;
              workspace[wp + 8 * 3] = dcval;
              workspace[wp + 8 * 4] = dcval;
              workspace[wp + 8 * 5] = dcval;
              workspace[wp + 8 * 6] = dcval;
              workspace[wp + 8 * 7] = dcval;
              ip++;
              qp++;
              wp++;
              continue;
            }
            z2 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z3 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            z1 = ((z2 + z3) * (4433));
            tmp2 = z1 + ((z3) * (-15137));
            tmp3 = z1 + ((z2) * (6270));
            z2 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            z3 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            tmp0 = ((int)((uint)(z2 + z3) << (13)));
            tmp1 = ((int)((uint)(z2 - z3) << (13)));
            tmp10 = tmp0 + tmp3;
            tmp13 = tmp0 - tmp3;
            tmp11 = tmp1 + tmp2;
            tmp12 = tmp1 - tmp2;
            tmp0 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp1 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            tmp2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            tmp3 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z1 = tmp0 + tmp3;
            z2 = tmp1 + tmp2;
            z3 = tmp0 + tmp2;
            z4 = tmp1 + tmp3;
            z5 = ((z3 + z4) * (9633));
            tmp0 = ((tmp0) * (2446));
            tmp1 = ((tmp1) * (16819));
            tmp2 = ((tmp2) * (25172));
            tmp3 = ((tmp3) * (12299));
            z1 = ((z1) * (-7373));
            z2 = ((z2) * (-20995));
            z3 = ((z3) * (-16069));
            z4 = ((z4) * (-3196));
            z3 += z5;
            z4 += z5;
            tmp0 += z1 + z3;
            tmp1 += z2 + z4;
            tmp2 += z2 + z3;
            tmp3 += z1 + z4;
            workspace[wp + 8 * 0] = (int)(((tmp10 + tmp3) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 7] = (int)(((tmp10 - tmp3) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 1] = (int)(((tmp11 + tmp2) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 6] = (int)(((tmp11 - tmp2) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 2] = (int)(((tmp12 + tmp1) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 5] = (int)(((tmp12 - tmp1) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 3] = (int)(((tmp13 + tmp0) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            workspace[wp + 8 * 4] = (int)(((tmp13 - tmp0) + (1 << ((13 - P1) - 1))) >> (13 - P1));
            ip++;
            qp++;
            wp++;
          }
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++) {
            op = (ctr) * stride;
            if (workspace[wp + 1] == 0 && workspace[wp + 2] == 0 && workspace[wp + 3] == 0 && workspace[wp + 4] == 0 &&
                workspace[wp + 5] == 0 && workspace[wp + 6] == 0 && workspace[wp + 7] == 0) {
              int dcval = rl[(int)((((int)workspace[wp + 0]) + (1 << ((P1 + 3) - 1))) >> (P1 + 3)) & mask];
              outp[op + 0] = dcval;
              outp[op + 1] = dcval;
              outp[op + 2] = dcval;
              outp[op + 3] = dcval;
              outp[op + 4] = dcval;
              outp[op + 5] = dcval;
              outp[op + 6] = dcval;
              outp[op + 7] = dcval;
              wp += 8;
              continue;
            }
            z2 = (int)workspace[wp + 2];
            z3 = (int)workspace[wp + 6];
            z1 = ((z2 + z3) * (4433));
            tmp2 = z1 + ((z3) * (-15137));
            tmp3 = z1 + ((z2) * (6270));
            tmp0 = ((int)((uint)((int)workspace[wp + 0] + (int)workspace[wp + 4]) << (13)));
            tmp1 = ((int)((uint)((int)workspace[wp + 0] - (int)workspace[wp + 4]) << (13)));
            tmp10 = tmp0 + tmp3;
            tmp13 = tmp0 - tmp3;
            tmp11 = tmp1 + tmp2;
            tmp12 = tmp1 - tmp2;
            tmp0 = (int)workspace[wp + 7];
            tmp1 = (int)workspace[wp + 5];
            tmp2 = (int)workspace[wp + 3];
            tmp3 = (int)workspace[wp + 1];
            z1 = tmp0 + tmp3;
            z2 = tmp1 + tmp2;
            z3 = tmp0 + tmp2;
            z4 = tmp1 + tmp3;
            z5 = ((z3 + z4) * (9633));
            tmp0 = ((tmp0) * (2446));
            tmp1 = ((tmp1) * (16819));
            tmp2 = ((tmp2) * (25172));
            tmp3 = ((tmp3) * (12299));
            z1 = ((z1) * (-7373));
            z2 = ((z2) * (-20995));
            z3 = ((z3) * (-16069));
            z4 = ((z4) * (-3196));
            z3 += z5;
            z4 += z5;
            tmp0 += z1 + z3;
            tmp1 += z2 + z4;
            tmp2 += z2 + z3;
            tmp3 += z1 + z4;
            outp[op + 0] = rl[(int)(((tmp10 + tmp3) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 7] = rl[(int)(((tmp10 - tmp3) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)(((tmp11 + tmp2) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 6] = rl[(int)(((tmp11 - tmp2) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)(((tmp12 + tmp1) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 5] = rl[(int)(((tmp12 - tmp1) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 3] = rl[(int)(((tmp13 + tmp0) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            outp[op + 4] = rl[(int)(((tmp13 - tmp0) + (1 << ((13 + P1 + 3) - 1))) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct7x7(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp2, tmp10, tmp11, tmp12, tmp13;
          int z1, z2, z3;
          int ctr;
          Span<int> workspace = stackalloc int[7 * 7];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 7; ctr++, ip++, qp++, wp++) {
            tmp13 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp13 = ((int)((uint)(tmp13) << (13)));
            tmp13 += 1 << (13 - P1 - 1);
            z1 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z2 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z3 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            tmp10 = ((z2 - z3) * (7223));
            tmp12 = ((z1 - z2) * (2578));
            tmp11 = tmp10 + tmp12 + tmp13 - ((z2) * (15083));
            tmp0 = z1 + z3;
            z2 -= tmp0;
            tmp0 = ((tmp0) * (10438)) + tmp13;
            tmp10 += tmp0 - ((z3) * (637));
            tmp12 += tmp0 - ((z1) * (20239));
            tmp13 += ((z2) * (11585));
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            tmp1 = ((z1 + z2) * (7663));
            tmp2 = ((z1 - z2) * (1395));
            tmp0 = tmp1 - tmp2;
            tmp1 += tmp2;
            tmp2 = ((z2 + z3) * (-11295));
            tmp1 += tmp2;
            z2 = ((z1 + z3) * (5027));
            tmp0 += z2;
            tmp2 += z2 + ((z3) * (15326));
            workspace[wp + 7 * 0] = (int)((tmp10 + tmp0) >> (13 - P1));
            workspace[wp + 7 * 6] = (int)((tmp10 - tmp0) >> (13 - P1));
            workspace[wp + 7 * 1] = (int)((tmp11 + tmp1) >> (13 - P1));
            workspace[wp + 7 * 5] = (int)((tmp11 - tmp1) >> (13 - P1));
            workspace[wp + 7 * 2] = (int)((tmp12 + tmp2) >> (13 - P1));
            workspace[wp + 7 * 4] = (int)((tmp12 - tmp2) >> (13 - P1));
            workspace[wp + 7 * 3] = (int)((tmp13) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 7; ctr++) {
            op = (ctr) * stride;
            tmp13 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp13 = ((int)((uint)(tmp13) << (13)));
            z1 = (int)workspace[wp + 2];
            z2 = (int)workspace[wp + 4];
            z3 = (int)workspace[wp + 6];
            tmp10 = ((z2 - z3) * (7223));
            tmp12 = ((z1 - z2) * (2578));
            tmp11 = tmp10 + tmp12 + tmp13 - ((z2) * (15083));
            tmp0 = z1 + z3;
            z2 -= tmp0;
            tmp0 = ((tmp0) * (10438)) + tmp13;
            tmp10 += tmp0 - ((z3) * (637));
            tmp12 += tmp0 - ((z1) * (20239));
            tmp13 += ((z2) * (11585));
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            tmp1 = ((z1 + z2) * (7663));
            tmp2 = ((z1 - z2) * (1395));
            tmp0 = tmp1 - tmp2;
            tmp1 += tmp2;
            tmp2 = ((z2 + z3) * (-11295));
            tmp1 += tmp2;
            z2 = ((z1 + z3) * (5027));
            tmp0 += z2;
            tmp2 += z2 + ((z3) * (15326));
            outp[op + 0] = rl[(int)((tmp10 + tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 6] = rl[(int)((tmp10 - tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)((tmp11 + tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 5] = rl[(int)((tmp11 - tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)((tmp12 + tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 4] = rl[(int)((tmp12 - tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 3] = rl[(int)((tmp13) >> (13 + P1 + 3)) & mask];
            wp += 7;
          }
        }
    }

    private static void LjIdct6x6(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp2, tmp10, tmp11, tmp12;
          int z1, z2, z3;
          int ctr;
          Span<int> workspace = stackalloc int[6 * 6];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 6; ctr++, ip++, qp++, wp++) {
            tmp0 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            tmp0 += 1 << (13 - P1 - 1);
            tmp2 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            tmp10 = ((tmp2) * (5793));
            tmp1 = tmp0 + tmp10;
            tmp11 = ((tmp0 - tmp10 - tmp10) >> (13 - P1));
            tmp10 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            tmp0 = ((tmp10) * (10033));
            tmp10 = tmp1 + tmp0;
            tmp12 = tmp1 - tmp0;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            tmp1 = ((z1 + z3) * (2998));
            tmp0 = tmp1 + ((int)((uint)(z1 + z2) << (13)));
            tmp2 = tmp1 + ((int)((uint)(z3 - z2) << (13)));
            tmp1 = ((int)((uint)(z1 - z2 - z3) << (P1)));
            workspace[wp + 6 * 0] = (int)((tmp10 + tmp0) >> (13 - P1));
            workspace[wp + 6 * 5] = (int)((tmp10 - tmp0) >> (13 - P1));
            workspace[wp + 6 * 1] = (int)(tmp11 + tmp1);
            workspace[wp + 6 * 4] = (int)(tmp11 - tmp1);
            workspace[wp + 6 * 2] = (int)((tmp12 + tmp2) >> (13 - P1));
            workspace[wp + 6 * 3] = (int)((tmp12 - tmp2) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 6; ctr++) {
            op = (ctr) * stride;
            tmp0 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            tmp2 = (int)workspace[wp + 4];
            tmp10 = ((tmp2) * (5793));
            tmp1 = tmp0 + tmp10;
            tmp11 = tmp0 - tmp10 - tmp10;
            tmp10 = (int)workspace[wp + 2];
            tmp0 = ((tmp10) * (10033));
            tmp10 = tmp1 + tmp0;
            tmp12 = tmp1 - tmp0;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            tmp1 = ((z1 + z3) * (2998));
            tmp0 = tmp1 + ((int)((uint)(z1 + z2) << (13)));
            tmp2 = tmp1 + ((int)((uint)(z3 - z2) << (13)));
            tmp1 = ((int)((uint)(z1 - z2 - z3) << (13)));
            outp[op + 0] = rl[(int)((tmp10 + tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 5] = rl[(int)((tmp10 - tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)((tmp11 + tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 4] = rl[(int)((tmp11 - tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)((tmp12 + tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 3] = rl[(int)((tmp12 - tmp2) >> (13 + P1 + 3)) & mask];
            wp += 6;
          }
        }
    }

    private static void LjIdct5x5(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp10, tmp11, tmp12;
          int z1, z2, z3;
          int ctr;
          Span<int> workspace = stackalloc int[5 * 5];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 5; ctr++, ip++, qp++, wp++) {
            tmp12 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp12 = ((int)((uint)(tmp12) << (13)));
            tmp12 += 1 << (13 - P1 - 1);
            tmp0 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            tmp1 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z1 = ((tmp0 + tmp1) * (6476));
            z2 = ((tmp0 - tmp1) * (2896));
            z3 = tmp12 + z2;
            tmp10 = z3 + z1;
            tmp11 = z3 - z1;
            tmp12 -= ((int)((uint)(z2) << (2)));
            z2 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z3 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z1 = ((z2 + z3) * (6810));
            tmp0 = z1 + ((z2) * (4209));
            tmp1 = z1 - ((z3) * (17828));
            workspace[wp + 5 * 0] = (int)((tmp10 + tmp0) >> (13 - P1));
            workspace[wp + 5 * 4] = (int)((tmp10 - tmp0) >> (13 - P1));
            workspace[wp + 5 * 1] = (int)((tmp11 + tmp1) >> (13 - P1));
            workspace[wp + 5 * 3] = (int)((tmp11 - tmp1) >> (13 - P1));
            workspace[wp + 5 * 2] = (int)((tmp12) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 5; ctr++) {
            op = (ctr) * stride;
            tmp12 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp12 = ((int)((uint)(tmp12) << (13)));
            tmp0 = (int)workspace[wp + 2];
            tmp1 = (int)workspace[wp + 4];
            z1 = ((tmp0 + tmp1) * (6476));
            z2 = ((tmp0 - tmp1) * (2896));
            z3 = tmp12 + z2;
            tmp10 = z3 + z1;
            tmp11 = z3 - z1;
            tmp12 -= ((int)((uint)(z2) << (2)));
            z2 = (int)workspace[wp + 1];
            z3 = (int)workspace[wp + 3];
            z1 = ((z2 + z3) * (6810));
            tmp0 = z1 + ((z2) * (4209));
            tmp1 = z1 - ((z3) * (17828));
            outp[op + 0] = rl[(int)((tmp10 + tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 4] = rl[(int)((tmp10 - tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)((tmp11 + tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 3] = rl[(int)((tmp11 - tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)((tmp12) >> (13 + P1 + 3)) & mask];
            wp += 5;
          }
        }
    }

    private static void LjIdct3x3(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp2, tmp10, tmp12;
          int ctr;
          Span<int> workspace = stackalloc int[3 * 3];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 3; ctr++, ip++, qp++, wp++) {
            tmp0 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            tmp0 += 1 << (13 - P1 - 1);
            tmp2 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            tmp12 = ((tmp2) * (5793));
            tmp10 = tmp0 + tmp12;
            tmp2 = tmp0 - tmp12 - tmp12;
            tmp12 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            tmp0 = ((tmp12) * (10033));
            workspace[wp + 3 * 0] = (int)((tmp10 + tmp0) >> (13 - P1));
            workspace[wp + 3 * 2] = (int)((tmp10 - tmp0) >> (13 - P1));
            workspace[wp + 3 * 1] = (int)((tmp2) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 3; ctr++) {
            op = (ctr) * stride;
            tmp0 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            tmp2 = (int)workspace[wp + 2];
            tmp12 = ((tmp2) * (5793));
            tmp10 = tmp0 + tmp12;
            tmp2 = tmp0 - tmp12 - tmp12;
            tmp12 = (int)workspace[wp + 1];
            tmp0 = ((tmp12) * (10033));
            outp[op + 0] = rl[(int)((tmp10 + tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)((tmp10 - tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)((tmp2) >> (13 + P1 + 3)) & mask];
            wp += 3;
          }
        }
    }

    private static void LjIdct9x9(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp2, tmp3, tmp10, tmp11, tmp12, tmp13, tmp14;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 9];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            tmp0 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            tmp0 += 1 << (13 - P1 - 1);
            z1 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z2 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z3 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            tmp3 = ((z3) * (5793));
            tmp1 = tmp0 + tmp3;
            tmp2 = tmp0 - tmp3 - tmp3;
            tmp0 = ((z1 - z2) * (5793));
            tmp11 = tmp2 + tmp0;
            tmp14 = tmp2 - tmp0 - tmp0;
            tmp0 = ((z1 + z2) * (10887));
            tmp2 = ((z1) * (8875));
            tmp3 = ((z2) * (2012));
            tmp10 = tmp1 + tmp0 - tmp3;
            tmp12 = tmp1 - tmp0 + tmp2;
            tmp13 = tmp1 - tmp2 + tmp3;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            z2 = ((z2) * (-10033));
            tmp2 = ((z1 + z3) * (7447));
            tmp3 = ((z1 + z4) * (3962));
            tmp0 = tmp2 + tmp3 - z2;
            tmp1 = ((z3 - z4) * (11409));
            tmp2 += z2 - tmp1;
            tmp3 += z2 + tmp1;
            tmp1 = ((z1 - z3 - z4) * (10033));
            workspace[wp + 8 * 0] = (int)((tmp10 + tmp0) >> (13 - P1));
            workspace[wp + 8 * 8] = (int)((tmp10 - tmp0) >> (13 - P1));
            workspace[wp + 8 * 1] = (int)((tmp11 + tmp1) >> (13 - P1));
            workspace[wp + 8 * 7] = (int)((tmp11 - tmp1) >> (13 - P1));
            workspace[wp + 8 * 2] = (int)((tmp12 + tmp2) >> (13 - P1));
            workspace[wp + 8 * 6] = (int)((tmp12 - tmp2) >> (13 - P1));
            workspace[wp + 8 * 3] = (int)((tmp13 + tmp3) >> (13 - P1));
            workspace[wp + 8 * 5] = (int)((tmp13 - tmp3) >> (13 - P1));
            workspace[wp + 8 * 4] = (int)((tmp14) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 9; ctr++) {
            op = (ctr) * stride;
            tmp0 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            z1 = (int)workspace[wp + 2];
            z2 = (int)workspace[wp + 4];
            z3 = (int)workspace[wp + 6];
            tmp3 = ((z3) * (5793));
            tmp1 = tmp0 + tmp3;
            tmp2 = tmp0 - tmp3 - tmp3;
            tmp0 = ((z1 - z2) * (5793));
            tmp11 = tmp2 + tmp0;
            tmp14 = tmp2 - tmp0 - tmp0;
            tmp0 = ((z1 + z2) * (10887));
            tmp2 = ((z1) * (8875));
            tmp3 = ((z2) * (2012));
            tmp10 = tmp1 + tmp0 - tmp3;
            tmp12 = tmp1 - tmp0 + tmp2;
            tmp13 = tmp1 - tmp2 + tmp3;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z4 = (int)workspace[wp + 7];
            z2 = ((z2) * (-10033));
            tmp2 = ((z1 + z3) * (7447));
            tmp3 = ((z1 + z4) * (3962));
            tmp0 = tmp2 + tmp3 - z2;
            tmp1 = ((z3 - z4) * (11409));
            tmp2 += z2 - tmp1;
            tmp3 += z2 + tmp1;
            tmp1 = ((z1 - z3 - z4) * (10033));
            outp[op + 0] = rl[(int)((tmp10 + tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 8] = rl[(int)((tmp10 - tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)((tmp11 + tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 7] = rl[(int)((tmp11 - tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)((tmp12 + tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 6] = rl[(int)((tmp12 - tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 3] = rl[(int)((tmp13 + tmp3) >> (13 + P1 + 3)) & mask];
            outp[op + 5] = rl[(int)((tmp13 - tmp3) >> (13 + P1 + 3)) & mask];
            outp[op + 4] = rl[(int)((tmp14) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct10x10(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp10, tmp11, tmp12, tmp13, tmp14;
          int tmp20, tmp21, tmp22, tmp23, tmp24;
          int z1, z2, z3, z4, z5;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 10];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            z3 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            z3 = ((int)((uint)(z3) << (13)));
            z3 += 1 << (13 - P1 - 1);
            z4 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z1 = ((z4) * (9373));
            z2 = ((z4) * (3580));
            tmp10 = z3 + z1;
            tmp11 = z3 - z2;
            tmp22 = ((z3 - ((int)((uint)(z1 - z2) << (1)))) >> (13 - P1));
            z2 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z3 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            z1 = ((z2 + z3) * (6810));
            tmp12 = z1 + ((z2) * (4209));
            tmp13 = z1 - ((z3) * (17828));
            tmp20 = tmp10 + tmp12;
            tmp24 = tmp10 - tmp12;
            tmp21 = tmp11 + tmp13;
            tmp23 = tmp11 - tmp13;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp11 = z2 + z4;
            tmp13 = z2 - z4;
            tmp12 = ((tmp13) * (2531));
            z5 = ((int)((uint)(z3) << (13)));
            z2 = ((tmp11) * (7791));
            z4 = z5 + tmp12;
            tmp10 = ((z1) * (11443)) + z2 + z4;
            tmp14 = ((z1) * (1812)) - z2 + z4;
            z2 = ((tmp11) * (4815));
            z4 = z5 - tmp12 - ((int)((uint)(tmp13) << (13 - 1)));
            tmp12 = ((int)((uint)(z1 - tmp13 - z3) << (P1)));
            tmp11 = ((z1) * (10323)) - z2 - z4;
            tmp13 = ((z1) * (5260)) - z2 + z4;
            workspace[wp + 8 * 0] = (int)((tmp20 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 9] = (int)((tmp20 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 1] = (int)((tmp21 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 8] = (int)((tmp21 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 2] = (int)(tmp22 + tmp12);
            workspace[wp + 8 * 7] = (int)(tmp22 - tmp12);
            workspace[wp + 8 * 3] = (int)((tmp23 + tmp13) >> (13 - P1));
            workspace[wp + 8 * 6] = (int)((tmp23 - tmp13) >> (13 - P1));
            workspace[wp + 8 * 4] = (int)((tmp24 + tmp14) >> (13 - P1));
            workspace[wp + 8 * 5] = (int)((tmp24 - tmp14) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 10; ctr++) {
            op = (ctr) * stride;
            z3 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            z3 = ((int)((uint)(z3) << (13)));
            z4 = (int)workspace[wp + 4];
            z1 = ((z4) * (9373));
            z2 = ((z4) * (3580));
            tmp10 = z3 + z1;
            tmp11 = z3 - z2;
            tmp22 = z3 - ((int)((uint)(z1 - z2) << (1)));
            z2 = (int)workspace[wp + 2];
            z3 = (int)workspace[wp + 6];
            z1 = ((z2 + z3) * (6810));
            tmp12 = z1 + ((z2) * (4209));
            tmp13 = z1 - ((z3) * (17828));
            tmp20 = tmp10 + tmp12;
            tmp24 = tmp10 - tmp12;
            tmp21 = tmp11 + tmp13;
            tmp23 = tmp11 - tmp13;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z3 = ((int)((uint)(z3) << (13)));
            z4 = (int)workspace[wp + 7];
            tmp11 = z2 + z4;
            tmp13 = z2 - z4;
            tmp12 = ((tmp13) * (2531));
            z2 = ((tmp11) * (7791));
            z4 = z3 + tmp12;
            tmp10 = ((z1) * (11443)) + z2 + z4;
            tmp14 = ((z1) * (1812)) - z2 + z4;
            z2 = ((tmp11) * (4815));
            z4 = z3 - tmp12 - ((int)((uint)(tmp13) << (13 - 1)));
            tmp12 = ((int)((uint)(z1 - tmp13) << (13))) - z3;
            tmp11 = ((z1) * (10323)) - z2 - z4;
            tmp13 = ((z1) * (5260)) - z2 + z4;
            outp[op + 0] = rl[(int)((tmp20 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 9] = rl[(int)((tmp20 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 1] = rl[(int)((tmp21 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 8] = rl[(int)((tmp21 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 2] = rl[(int)((tmp22 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 7] = rl[(int)((tmp22 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 3] = rl[(int)((tmp23 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 6] = rl[(int)((tmp23 - tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 4] = rl[(int)((tmp24 + tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 5] = rl[(int)((tmp24 - tmp14) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct11x11(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp10, tmp11, tmp12, tmp13, tmp14;
          int tmp20, tmp21, tmp22, tmp23, tmp24, tmp25;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 11];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            tmp10 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp10 = ((int)((uint)(tmp10) << (13)));
            tmp10 += 1 << (13 - P1 - 1);
            z1 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z2 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z3 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            tmp20 = ((z2 - z3) * (20862));
            tmp23 = ((z2 - z1) * (3529));
            z4 = z1 + z3;
            tmp24 = ((z4) * (-9467));
            z4 -= z2;
            tmp25 = tmp10 + ((z4) * (11116));
            tmp21 = tmp20 + tmp23 + tmp25 -
                    ((z2) * (14924));
            tmp20 += tmp25 + ((z3) * (17333));
            tmp23 += tmp25 - ((z1) * (12399));
            tmp24 += tmp25;
            tmp22 = tmp24 - ((z3) * (6461));
            tmp24 += ((z2) * (15929)) -
                     ((z1) * (11395));
            tmp25 = tmp10 - ((z4) * (11585));
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp11 = z1 + z2;
            tmp14 = ((tmp11 + z3 + z4) * (3264));
            tmp11 = ((tmp11) * (7274));
            tmp12 = ((z1 + z3) * (5492));
            tmp13 = tmp14 + ((z1 + z4) * (3000));
            tmp10 = tmp11 + tmp12 + tmp13 -
                    ((z1) * (7562));
            z1    = tmp14 - ((z2 + z3) * (9527));
            tmp11 += z1 + ((z2) * (16984));
            tmp12 += z1 - ((z3) * (9766));
            z1    = ((z2 + z4) * (-14731));
            tmp11 += z1;
            tmp13 += z1 + ((z4) * (17223));
            tmp14 += ((z2) * (-12019)) +
                     ((z3) * (8203)) -
                     ((z4) * (13802));
            workspace[wp + 8 * 0]  = (int)((tmp20 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 10] = (int)((tmp20 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 1]  = (int)((tmp21 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 9]  = (int)((tmp21 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 2]  = (int)((tmp22 + tmp12) >> (13 - P1));
            workspace[wp + 8 * 8]  = (int)((tmp22 - tmp12) >> (13 - P1));
            workspace[wp + 8 * 3]  = (int)((tmp23 + tmp13) >> (13 - P1));
            workspace[wp + 8 * 7]  = (int)((tmp23 - tmp13) >> (13 - P1));
            workspace[wp + 8 * 4]  = (int)((tmp24 + tmp14) >> (13 - P1));
            workspace[wp + 8 * 6]  = (int)((tmp24 - tmp14) >> (13 - P1));
            workspace[wp + 8 * 5]  = (int)((tmp25) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 11; ctr++) {
            op = (ctr) * stride;
            tmp10 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp10 = ((int)((uint)(tmp10) << (13)));
            z1 = (int)workspace[wp + 2];
            z2 = (int)workspace[wp + 4];
            z3 = (int)workspace[wp + 6];
            tmp20 = ((z2 - z3) * (20862));
            tmp23 = ((z2 - z1) * (3529));
            z4 = z1 + z3;
            tmp24 = ((z4) * (-9467));
            z4 -= z2;
            tmp25 = tmp10 + ((z4) * (11116));
            tmp21 = tmp20 + tmp23 + tmp25 -
                    ((z2) * (14924));
            tmp20 += tmp25 + ((z3) * (17333));
            tmp23 += tmp25 - ((z1) * (12399));
            tmp24 += tmp25;
            tmp22 = tmp24 - ((z3) * (6461));
            tmp24 += ((z2) * (15929)) -
                     ((z1) * (11395));
            tmp25 = tmp10 - ((z4) * (11585));
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z4 = (int)workspace[wp + 7];
            tmp11 = z1 + z2;
            tmp14 = ((tmp11 + z3 + z4) * (3264));
            tmp11 = ((tmp11) * (7274));
            tmp12 = ((z1 + z3) * (5492));
            tmp13 = tmp14 + ((z1 + z4) * (3000));
            tmp10 = tmp11 + tmp12 + tmp13 -
                    ((z1) * (7562));
            z1    = tmp14 - ((z2 + z3) * (9527));
            tmp11 += z1 + ((z2) * (16984));
            tmp12 += z1 - ((z3) * (9766));
            z1    = ((z2 + z4) * (-14731));
            tmp11 += z1;
            tmp13 += z1 + ((z4) * (17223));
            tmp14 += ((z2) * (-12019)) +
                     ((z3) * (8203)) -
                     ((z4) * (13802));
            outp[op + 0]  = rl[(int)((tmp20 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 10] = rl[(int)((tmp20 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 1]  = rl[(int)((tmp21 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 9]  = rl[(int)((tmp21 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 2]  = rl[(int)((tmp22 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 8]  = rl[(int)((tmp22 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 3]  = rl[(int)((tmp23 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 7]  = rl[(int)((tmp23 - tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 4]  = rl[(int)((tmp24 + tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 6]  = rl[(int)((tmp24 - tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 5]  = rl[(int)((tmp25) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct12x12(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp10, tmp11, tmp12, tmp13, tmp14, tmp15;
          int tmp20, tmp21, tmp22, tmp23, tmp24, tmp25;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 12];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            z3 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            z3 = ((int)((uint)(z3) << (13)));
            z3 += 1 << (13 - P1 - 1);
            z4 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z4 = ((z4) * (10033));
            tmp10 = z3 + z4;
            tmp11 = z3 - z4;
            z1 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z4 = ((z1) * (11190));
            z1 = ((int)((uint)(z1) << (13)));
            z2 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            z2 = ((int)((uint)(z2) << (13)));
            tmp12 = z1 - z2;
            tmp21 = z3 + tmp12;
            tmp24 = z3 - tmp12;
            tmp12 = z4 + z2;
            tmp20 = tmp10 + tmp12;
            tmp25 = tmp10 - tmp12;
            tmp12 = z4 - z1 - z2;
            tmp22 = tmp11 + tmp12;
            tmp23 = tmp11 - tmp12;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp11 = ((z2) * (10703));
            tmp14 = ((z2) * (-4433));
            tmp10 = z1 + z3;
            tmp15 = ((tmp10 + z4) * (7053));
            tmp12 = tmp15 + ((tmp10) * (2139));
            tmp10 = tmp12 + tmp11 + ((z1) * (2295));
            tmp13 = ((z3 + z4) * (-8565));
            tmp12 += tmp13 + tmp14 - ((z3) * (12112));
            tmp13 += tmp15 - tmp11 + ((z4) * (12998));
            tmp15 += tmp14 - ((z1) * (5540)) -
                     ((z4) * (16244));
            z1 -= z4;
            z2 -= z3;
            z3 = ((z1 + z2) * (4433));
            tmp11 = z3 + ((z1) * (6270));
            tmp14 = z3 - ((z2) * (15137));
            workspace[wp + 8 * 0]  = (int)((tmp20 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 11] = (int)((tmp20 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 1]  = (int)((tmp21 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 10] = (int)((tmp21 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 2]  = (int)((tmp22 + tmp12) >> (13 - P1));
            workspace[wp + 8 * 9]  = (int)((tmp22 - tmp12) >> (13 - P1));
            workspace[wp + 8 * 3]  = (int)((tmp23 + tmp13) >> (13 - P1));
            workspace[wp + 8 * 8]  = (int)((tmp23 - tmp13) >> (13 - P1));
            workspace[wp + 8 * 4]  = (int)((tmp24 + tmp14) >> (13 - P1));
            workspace[wp + 8 * 7]  = (int)((tmp24 - tmp14) >> (13 - P1));
            workspace[wp + 8 * 5]  = (int)((tmp25 + tmp15) >> (13 - P1));
            workspace[wp + 8 * 6]  = (int)((tmp25 - tmp15) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 12; ctr++) {
            op = (ctr) * stride;
            z3 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            z3 = ((int)((uint)(z3) << (13)));
            z4 = (int)workspace[wp + 4];
            z4 = ((z4) * (10033));
            tmp10 = z3 + z4;
            tmp11 = z3 - z4;
            z1 = (int)workspace[wp + 2];
            z4 = ((z1) * (11190));
            z1 = ((int)((uint)(z1) << (13)));
            z2 = (int)workspace[wp + 6];
            z2 = ((int)((uint)(z2) << (13)));
            tmp12 = z1 - z2;
            tmp21 = z3 + tmp12;
            tmp24 = z3 - tmp12;
            tmp12 = z4 + z2;
            tmp20 = tmp10 + tmp12;
            tmp25 = tmp10 - tmp12;
            tmp12 = z4 - z1 - z2;
            tmp22 = tmp11 + tmp12;
            tmp23 = tmp11 - tmp12;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z4 = (int)workspace[wp + 7];
            tmp11 = ((z2) * (10703));
            tmp14 = ((z2) * (-4433));
            tmp10 = z1 + z3;
            tmp15 = ((tmp10 + z4) * (7053));
            tmp12 = tmp15 + ((tmp10) * (2139));
            tmp10 = tmp12 + tmp11 + ((z1) * (2295));
            tmp13 = ((z3 + z4) * (-8565));
            tmp12 += tmp13 + tmp14 - ((z3) * (12112));
            tmp13 += tmp15 - tmp11 + ((z4) * (12998));
            tmp15 += tmp14 - ((z1) * (5540)) -
                     ((z4) * (16244));
            z1 -= z4;
            z2 -= z3;
            z3 = ((z1 + z2) * (4433));
            tmp11 = z3 + ((z1) * (6270));
            tmp14 = z3 - ((z2) * (15137));
            outp[op + 0]  = rl[(int)((tmp20 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 11] = rl[(int)((tmp20 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 1]  = rl[(int)((tmp21 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 10] = rl[(int)((tmp21 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 2]  = rl[(int)((tmp22 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 9]  = rl[(int)((tmp22 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 3]  = rl[(int)((tmp23 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 8]  = rl[(int)((tmp23 - tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 4]  = rl[(int)((tmp24 + tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 7]  = rl[(int)((tmp24 - tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 5]  = rl[(int)((tmp25 + tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 6]  = rl[(int)((tmp25 - tmp15) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct13x13(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp10, tmp11, tmp12, tmp13, tmp14, tmp15;
          int tmp20, tmp21, tmp22, tmp23, tmp24, tmp25, tmp26;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 13];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            z1 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            z1 = ((int)((uint)(z1) << (13)));
            z1 += 1 << (13 - P1 - 1);
            z2 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z3 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z4 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            tmp10 = z3 + z4;
            tmp11 = z3 - z4;
            tmp12 = ((tmp10) * (9465));
            tmp13 = ((tmp11) * (793)) + z1;
            tmp20 = ((z2) * (11249)) + tmp12 + tmp13;
            tmp22 = ((z2) * (4108)) - tmp12 + tmp13;
            tmp12 = ((tmp10) * (2592));
            tmp13 = ((tmp11) * (3989)) + z1;
            tmp21 = ((z2) * (8672)) - tmp12 + tmp13;
            tmp25 = ((z2) * (-10258)) + tmp12 + tmp13;
            tmp12 = ((tmp10) * (3570));
            tmp13 = ((tmp11) * (7678)) - z1;
            tmp23 = ((z2) * (-1396)) - tmp12 - tmp13;
            tmp24 = ((z2) * (-6581)) + tmp12 - tmp13;
            tmp26 = ((tmp11 - z2) * (11585)) + z1;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp11 = ((z1 + z2) * (10832));
            tmp12 = ((z1 + z3) * (9534));
            tmp15 = z1 + z4;
            tmp13 = ((tmp15) * (7682));
            tmp10 = tmp11 + tmp12 + tmp13 -
                    ((z1) * (16549));
            tmp14 = ((z2 + z3) * (-2773));
            tmp11 += tmp14 + ((z2) * (6859));
            tmp12 += tmp14 - ((z3) * (12879));
            tmp14 = ((z2 + z4) * (-9534));
            tmp11 += tmp14;
            tmp13 += tmp14 + ((z4) * (18068));
            tmp14 = ((z3 + z4) * (-5384));
            tmp12 += tmp14;
            tmp13 += tmp14;
            tmp15 = ((tmp15) * (2773));
            tmp14 = tmp15 + ((z1) * (2611)) -
                    ((z2) * (3818));
            z1    = ((z3 - z2) * (7682));
            tmp14 += z1;
            tmp15 += z1 + ((z3) * (3150)) -
                     ((z4) * (14273));
            workspace[wp + 8 * 0]  = (int)((tmp20 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 12] = (int)((tmp20 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 1]  = (int)((tmp21 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 11] = (int)((tmp21 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 2]  = (int)((tmp22 + tmp12) >> (13 - P1));
            workspace[wp + 8 * 10] = (int)((tmp22 - tmp12) >> (13 - P1));
            workspace[wp + 8 * 3]  = (int)((tmp23 + tmp13) >> (13 - P1));
            workspace[wp + 8 * 9]  = (int)((tmp23 - tmp13) >> (13 - P1));
            workspace[wp + 8 * 4]  = (int)((tmp24 + tmp14) >> (13 - P1));
            workspace[wp + 8 * 8]  = (int)((tmp24 - tmp14) >> (13 - P1));
            workspace[wp + 8 * 5]  = (int)((tmp25 + tmp15) >> (13 - P1));
            workspace[wp + 8 * 7]  = (int)((tmp25 - tmp15) >> (13 - P1));
            workspace[wp + 8 * 6]  = (int)((tmp26) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 13; ctr++) {
            op = (ctr) * stride;
            z1 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            z1 = ((int)((uint)(z1) << (13)));
            z2 = (int)workspace[wp + 2];
            z3 = (int)workspace[wp + 4];
            z4 = (int)workspace[wp + 6];
            tmp10 = z3 + z4;
            tmp11 = z3 - z4;
            tmp12 = ((tmp10) * (9465));
            tmp13 = ((tmp11) * (793)) + z1;
            tmp20 = ((z2) * (11249)) + tmp12 + tmp13;
            tmp22 = ((z2) * (4108)) - tmp12 + tmp13;
            tmp12 = ((tmp10) * (2592));
            tmp13 = ((tmp11) * (3989)) + z1;
            tmp21 = ((z2) * (8672)) - tmp12 + tmp13;
            tmp25 = ((z2) * (-10258)) + tmp12 + tmp13;
            tmp12 = ((tmp10) * (3570));
            tmp13 = ((tmp11) * (7678)) - z1;
            tmp23 = ((z2) * (-1396)) - tmp12 - tmp13;
            tmp24 = ((z2) * (-6581)) + tmp12 - tmp13;
            tmp26 = ((tmp11 - z2) * (11585)) + z1;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z4 = (int)workspace[wp + 7];
            tmp11 = ((z1 + z2) * (10832));
            tmp12 = ((z1 + z3) * (9534));
            tmp15 = z1 + z4;
            tmp13 = ((tmp15) * (7682));
            tmp10 = tmp11 + tmp12 + tmp13 -
                    ((z1) * (16549));
            tmp14 = ((z2 + z3) * (-2773));
            tmp11 += tmp14 + ((z2) * (6859));
            tmp12 += tmp14 - ((z3) * (12879));
            tmp14 = ((z2 + z4) * (-9534));
            tmp11 += tmp14;
            tmp13 += tmp14 + ((z4) * (18068));
            tmp14 = ((z3 + z4) * (-5384));
            tmp12 += tmp14;
            tmp13 += tmp14;
            tmp15 = ((tmp15) * (2773));
            tmp14 = tmp15 + ((z1) * (2611)) -
                    ((z2) * (3818));
            z1    = ((z3 - z2) * (7682));
            tmp14 += z1;
            tmp15 += z1 + ((z3) * (3150)) -
                     ((z4) * (14273));
            outp[op + 0]  = rl[(int)((tmp20 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 12] = rl[(int)((tmp20 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 1]  = rl[(int)((tmp21 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 11] = rl[(int)((tmp21 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 2]  = rl[(int)((tmp22 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 10] = rl[(int)((tmp22 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 3]  = rl[(int)((tmp23 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 9]  = rl[(int)((tmp23 - tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 4]  = rl[(int)((tmp24 + tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 8]  = rl[(int)((tmp24 - tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 5]  = rl[(int)((tmp25 + tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 7]  = rl[(int)((tmp25 - tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 6]  = rl[(int)((tmp26) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct14x14(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp10, tmp11, tmp12, tmp13, tmp14, tmp15, tmp16;
          int tmp20, tmp21, tmp22, tmp23, tmp24, tmp25, tmp26;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 14];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            z1 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            z1 = ((int)((uint)(z1) << (13)));
            z1 += 1 << (13 - P1 - 1);
            z4 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z2 = ((z4) * (10438));
            z3 = ((z4) * (2578));
            z4 = ((z4) * (7223));
            tmp10 = z1 + z2;
            tmp11 = z1 + z3;
            tmp12 = z1 - z4;
            tmp23 = ((z1 - ((int)((uint)(z2 + z3 - z4) << (1)))) >> (13 - P1));
            z1 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z2 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            z3 = ((z1 + z2) * (9058));
            tmp13 = z3 + ((z1) * (2237));
            tmp14 = z3 - ((z2) * (14084));
            tmp15 = ((z1) * (5027)) -
                    ((z2) * (11295));
            tmp20 = tmp10 + tmp13;
            tmp26 = tmp10 - tmp13;
            tmp21 = tmp11 + tmp14;
            tmp25 = tmp11 - tmp14;
            tmp22 = tmp12 + tmp15;
            tmp24 = tmp12 - tmp15;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp13 = ((int)((uint)(z4) << (13)));
            tmp14 = z1 + z3;
            tmp11 = ((z1 + z2) * (10935));
            tmp12 = ((tmp14) * (9810));
            tmp10 = tmp11 + tmp12 + tmp13 - ((z1) * (9232));
            tmp14 = ((tmp14) * (6164));
            tmp16 = tmp14 - ((z1) * (8693));
            z1    -= z2;
            tmp15 = ((z1) * (3826)) - tmp13;
            tmp16 += tmp15;
            z1    += z4;
            z4    = ((z2 + z3) * (-1297)) - tmp13;
            tmp11 += z4 - ((z2) * (3474));
            tmp12 += z4 - ((z3) * (19447));
            z4    = ((z3 - z2) * (11512));
            tmp14 += z4 + tmp13 - ((z3) * (13850));
            tmp15 += z4 + ((z2) * (5529));
            tmp13 = ((int)((uint)(z1 - z3) << (P1)));
            workspace[wp + 8 * 0]  = (int)((tmp20 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 13] = (int)((tmp20 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 1]  = (int)((tmp21 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 12] = (int)((tmp21 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 2]  = (int)((tmp22 + tmp12) >> (13 - P1));
            workspace[wp + 8 * 11] = (int)((tmp22 - tmp12) >> (13 - P1));
            workspace[wp + 8 * 3]  = (int)(tmp23 + tmp13);
            workspace[wp + 8 * 10] = (int)(tmp23 - tmp13);
            workspace[wp + 8 * 4]  = (int)((tmp24 + tmp14) >> (13 - P1));
            workspace[wp + 8 * 9]  = (int)((tmp24 - tmp14) >> (13 - P1));
            workspace[wp + 8 * 5]  = (int)((tmp25 + tmp15) >> (13 - P1));
            workspace[wp + 8 * 8]  = (int)((tmp25 - tmp15) >> (13 - P1));
            workspace[wp + 8 * 6]  = (int)((tmp26 + tmp16) >> (13 - P1));
            workspace[wp + 8 * 7]  = (int)((tmp26 - tmp16) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 14; ctr++) {
            op = (ctr) * stride;
            z1 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            z1 = ((int)((uint)(z1) << (13)));
            z4 = (int)workspace[wp + 4];
            z2 = ((z4) * (10438));
            z3 = ((z4) * (2578));
            z4 = ((z4) * (7223));
            tmp10 = z1 + z2;
            tmp11 = z1 + z3;
            tmp12 = z1 - z4;
            tmp23 = z1 - ((int)((uint)(z2 + z3 - z4) << (1)));
            z1 = (int)workspace[wp + 2];
            z2 = (int)workspace[wp + 6];
            z3 = ((z1 + z2) * (9058));
            tmp13 = z3 + ((z1) * (2237));
            tmp14 = z3 - ((z2) * (14084));
            tmp15 = ((z1) * (5027)) -
                    ((z2) * (11295));
            tmp20 = tmp10 + tmp13;
            tmp26 = tmp10 - tmp13;
            tmp21 = tmp11 + tmp14;
            tmp25 = tmp11 - tmp14;
            tmp22 = tmp12 + tmp15;
            tmp24 = tmp12 - tmp15;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z4 = (int)workspace[wp + 7];
            z4 = ((int)((uint)(z4) << (13)));
            tmp14 = z1 + z3;
            tmp11 = ((z1 + z2) * (10935));
            tmp12 = ((tmp14) * (9810));
            tmp10 = tmp11 + tmp12 + z4 - ((z1) * (9232));
            tmp14 = ((tmp14) * (6164));
            tmp16 = tmp14 - ((z1) * (8693));
            z1    -= z2;
            tmp15 = ((z1) * (3826)) - z4;
            tmp16 += tmp15;
            tmp13 = ((z2 + z3) * (-1297)) - z4;
            tmp11 += tmp13 - ((z2) * (3474));
            tmp12 += tmp13 - ((z3) * (19447));
            tmp13 = ((z3 - z2) * (11512));
            tmp14 += tmp13 + z4 - ((z3) * (13850));
            tmp15 += tmp13 + ((z2) * (5529));
            tmp13 = ((int)((uint)(z1 - z3) << (13))) + z4;
            outp[op + 0]  = rl[(int)((tmp20 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 13] = rl[(int)((tmp20 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 1]  = rl[(int)((tmp21 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 12] = rl[(int)((tmp21 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 2]  = rl[(int)((tmp22 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 11] = rl[(int)((tmp22 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 3]  = rl[(int)((tmp23 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 10] = rl[(int)((tmp23 - tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 4]  = rl[(int)((tmp24 + tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 9]  = rl[(int)((tmp24 - tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 5]  = rl[(int)((tmp25 + tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 8]  = rl[(int)((tmp25 - tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 6]  = rl[(int)((tmp26 + tmp16) >> (13 + P1 + 3)) & mask];
            outp[op + 7]  = rl[(int)((tmp26 - tmp16) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct15x15(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp10, tmp11, tmp12, tmp13, tmp14, tmp15, tmp16;
          int tmp20, tmp21, tmp22, tmp23, tmp24, tmp25, tmp26, tmp27;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 15];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            z1 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            z1 = ((int)((uint)(z1) << (13)));
            z1 += 1 << (13 - P1 - 1);
            z2 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z3 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            z4 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            tmp10 = ((z4) * (3580));
            tmp11 = ((z4) * (9373));
            tmp12 = z1 - tmp10;
            tmp13 = z1 + tmp11;
            z1 -= ((int)((uint)(tmp11 - tmp10) << (1)));
            z4 = z2 - z3;
            z3 += z2;
            tmp10 = ((z3) * (10958));
            tmp11 = ((z4) * (374));
            z2 = ((z2) * (11795));
            tmp20 = tmp13 + tmp10 + tmp11;
            tmp23 = tmp12 - tmp10 + tmp11 + z2;
            tmp10 = ((z3) * (4482));
            tmp11 = ((z4) * (3271));
            tmp25 = tmp13 - tmp10 - tmp11;
            tmp26 = tmp12 + tmp10 - tmp11 - z2;
            tmp10 = ((z3) * (6476));
            tmp11 = ((z4) * (2896));
            tmp21 = tmp12 + tmp10 + tmp11;
            tmp24 = tmp13 - tmp10 + tmp11;
            tmp11 += tmp11;
            tmp22 = z1 + tmp11;
            tmp27 = z1 - tmp11 - tmp11;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z4 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z3 = ((z4) * (10033));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp13 = z2 - z4;
            tmp15 = ((z1 + tmp13) * (6810));
            tmp11 = tmp15 + ((z1) * (4209));
            tmp14 = tmp15 - ((tmp13) * (17828));
            tmp13 = ((z2) * (-6810));
            tmp15 = ((z2) * (-11018));
            z2 = z1 - z4;
            tmp12 = z3 + ((z2) * (11522));
            tmp10 = tmp12 + ((z4) * (20131)) - tmp15;
            tmp16 = tmp12 - ((z1) * (9113)) + tmp13;
            tmp12 = ((z2) * (10033)) - z3;
            z2 = ((z1 + z4) * (4712));
            tmp13 += z2 + ((z1) * (3897)) - z3;
            tmp15 += z2 - ((z4) * (7121)) + z3;
            workspace[wp + 8 * 0]  = (int)((tmp20 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 14] = (int)((tmp20 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 1]  = (int)((tmp21 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 13] = (int)((tmp21 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 2]  = (int)((tmp22 + tmp12) >> (13 - P1));
            workspace[wp + 8 * 12] = (int)((tmp22 - tmp12) >> (13 - P1));
            workspace[wp + 8 * 3]  = (int)((tmp23 + tmp13) >> (13 - P1));
            workspace[wp + 8 * 11] = (int)((tmp23 - tmp13) >> (13 - P1));
            workspace[wp + 8 * 4]  = (int)((tmp24 + tmp14) >> (13 - P1));
            workspace[wp + 8 * 10] = (int)((tmp24 - tmp14) >> (13 - P1));
            workspace[wp + 8 * 5]  = (int)((tmp25 + tmp15) >> (13 - P1));
            workspace[wp + 8 * 9]  = (int)((tmp25 - tmp15) >> (13 - P1));
            workspace[wp + 8 * 6]  = (int)((tmp26 + tmp16) >> (13 - P1));
            workspace[wp + 8 * 8]  = (int)((tmp26 - tmp16) >> (13 - P1));
            workspace[wp + 8 * 7]  = (int)((tmp27) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 15; ctr++) {
            op = (ctr) * stride;
            z1 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            z1 = ((int)((uint)(z1) << (13)));
            z2 = (int)workspace[wp + 2];
            z3 = (int)workspace[wp + 4];
            z4 = (int)workspace[wp + 6];
            tmp10 = ((z4) * (3580));
            tmp11 = ((z4) * (9373));
            tmp12 = z1 - tmp10;
            tmp13 = z1 + tmp11;
            z1 -= ((int)((uint)(tmp11 - tmp10) << (1)));
            z4 = z2 - z3;
            z3 += z2;
            tmp10 = ((z3) * (10958));
            tmp11 = ((z4) * (374));
            z2 = ((z2) * (11795));
            tmp20 = tmp13 + tmp10 + tmp11;
            tmp23 = tmp12 - tmp10 + tmp11 + z2;
            tmp10 = ((z3) * (4482));
            tmp11 = ((z4) * (3271));
            tmp25 = tmp13 - tmp10 - tmp11;
            tmp26 = tmp12 + tmp10 - tmp11 - z2;
            tmp10 = ((z3) * (6476));
            tmp11 = ((z4) * (2896));
            tmp21 = tmp12 + tmp10 + tmp11;
            tmp24 = tmp13 - tmp10 + tmp11;
            tmp11 += tmp11;
            tmp22 = z1 + tmp11;
            tmp27 = z1 - tmp11 - tmp11;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z4 = (int)workspace[wp + 5];
            z3 = ((z4) * (10033));
            z4 = (int)workspace[wp + 7];
            tmp13 = z2 - z4;
            tmp15 = ((z1 + tmp13) * (6810));
            tmp11 = tmp15 + ((z1) * (4209));
            tmp14 = tmp15 - ((tmp13) * (17828));
            tmp13 = ((z2) * (-6810));
            tmp15 = ((z2) * (-11018));
            z2 = z1 - z4;
            tmp12 = z3 + ((z2) * (11522));
            tmp10 = tmp12 + ((z4) * (20131)) - tmp15;
            tmp16 = tmp12 - ((z1) * (9113)) + tmp13;
            tmp12 = ((z2) * (10033)) - z3;
            z2 = ((z1 + z4) * (4712));
            tmp13 += z2 + ((z1) * (3897)) - z3;
            tmp15 += z2 - ((z4) * (7121)) + z3;
            outp[op + 0]  = rl[(int)((tmp20 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 14] = rl[(int)((tmp20 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 1]  = rl[(int)((tmp21 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 13] = rl[(int)((tmp21 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 2]  = rl[(int)((tmp22 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 12] = rl[(int)((tmp22 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 3]  = rl[(int)((tmp23 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 11] = rl[(int)((tmp23 - tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 4]  = rl[(int)((tmp24 + tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 10] = rl[(int)((tmp24 - tmp14) >> (13 + P1 + 3)) & mask];
            outp[op + 5]  = rl[(int)((tmp25 + tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 9]  = rl[(int)((tmp25 - tmp15) >> (13 + P1 + 3)) & mask];
            outp[op + 6]  = rl[(int)((tmp26 + tmp16) >> (13 + P1 + 3)) & mask];
            outp[op + 8]  = rl[(int)((tmp26 - tmp16) >> (13 + P1 + 3)) & mask];
            outp[op + 7]  = rl[(int)((tmp27) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct16x16(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp2, tmp3, tmp10, tmp11, tmp12, tmp13;
          int tmp20, tmp21, tmp22, tmp23, tmp24, tmp25, tmp26, tmp27;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 16];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++, ip++, qp++, wp++) {
            tmp0 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            tmp0 += 1 << (13 - P1 - 1);
            z1 = ((coef[ip + 8 * 4]) * (q[qp + 8 * 4]));
            tmp1 = ((z1) * (10703));
            tmp2 = ((z1) * (4433));
            tmp10 = tmp0 + tmp1;
            tmp11 = tmp0 - tmp1;
            tmp12 = tmp0 + tmp2;
            tmp13 = tmp0 - tmp2;
            z1 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z2 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            z3 = z1 - z2;
            z4 = ((z3) * (2260));
            z3 = ((z3) * (11363));
            tmp0 = z3 + ((z2) * (20995));
            tmp1 = z4 + ((z1) * (7373));
            tmp2 = z3 - ((z1) * (4926));
            tmp3 = z4 - ((z2) * (4176));
            tmp20 = tmp10 + tmp0;
            tmp27 = tmp10 - tmp0;
            tmp21 = tmp12 + tmp1;
            tmp26 = tmp12 - tmp1;
            tmp22 = tmp13 + tmp2;
            tmp25 = tmp13 - tmp2;
            tmp23 = tmp11 + tmp3;
            tmp24 = tmp11 - tmp3;
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            z2 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z3 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z4 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp11 = z1 + z3;
            tmp1  = ((z1 + z2) * (11086));
            tmp2  = ((tmp11) * (10217));
            tmp3  = ((z1 + z4) * (8956));
            tmp10 = ((z1 - z4) * (7350));
            tmp11 = ((tmp11) * (5461));
            tmp12 = ((z1 - z2) * (3363));
            tmp0  = tmp1 + tmp2 + tmp3 -
                    ((z1) * (18730));
            tmp13 = tmp10 + tmp11 + tmp12 -
                    ((z1) * (15038));
            z1    = ((z2 + z3) * (1136));
            tmp1  += z1 + ((z2) * (589));
            tmp2  += z1 - ((z3) * (9222));
            z1    = ((z3 - z2) * (11529));
            tmp11 += z1 - ((z3) * (6278));
            tmp12 += z1 + ((z2) * (16154));
            z2    += z4;
            z1    = ((z2) * (-5461));
            tmp1  += z1;
            tmp3  += z1 + ((z4) * (8728));
            z2    = ((z2) * (-10217));
            tmp10 += z2 + ((z4) * (25733));
            tmp12 += z2;
            z2    = ((z3 + z4) * (-11086));
            tmp2  += z2;
            tmp3  += z2;
            z2    = ((z4 - z3) * (3363));
            tmp10 += z2;
            tmp11 += z2;
            workspace[wp + 8 * 0]  = (int)((tmp20 + tmp0) >> (13 - P1));
            workspace[wp + 8 * 15] = (int)((tmp20 - tmp0) >> (13 - P1));
            workspace[wp + 8 * 1]  = (int)((tmp21 + tmp1) >> (13 - P1));
            workspace[wp + 8 * 14] = (int)((tmp21 - tmp1) >> (13 - P1));
            workspace[wp + 8 * 2]  = (int)((tmp22 + tmp2) >> (13 - P1));
            workspace[wp + 8 * 13] = (int)((tmp22 - tmp2) >> (13 - P1));
            workspace[wp + 8 * 3]  = (int)((tmp23 + tmp3) >> (13 - P1));
            workspace[wp + 8 * 12] = (int)((tmp23 - tmp3) >> (13 - P1));
            workspace[wp + 8 * 4]  = (int)((tmp24 + tmp10) >> (13 - P1));
            workspace[wp + 8 * 11] = (int)((tmp24 - tmp10) >> (13 - P1));
            workspace[wp + 8 * 5]  = (int)((tmp25 + tmp11) >> (13 - P1));
            workspace[wp + 8 * 10] = (int)((tmp25 - tmp11) >> (13 - P1));
            workspace[wp + 8 * 6]  = (int)((tmp26 + tmp12) >> (13 - P1));
            workspace[wp + 8 * 9]  = (int)((tmp26 - tmp12) >> (13 - P1));
            workspace[wp + 8 * 7]  = (int)((tmp27 + tmp13) >> (13 - P1));
            workspace[wp + 8 * 8]  = (int)((tmp27 - tmp13) >> (13 - P1));
          }
          wp = 0;
          for (ctr = 0; ctr < 16; ctr++) {
            op = (ctr) * stride;
            tmp0 = (int)workspace[wp + 0] + (1 << (P1 + 2));
            tmp0 = ((int)((uint)(tmp0) << (13)));
            z1 = (int)workspace[wp + 4];
            tmp1 = ((z1) * (10703));
            tmp2 = ((z1) * (4433));
            tmp10 = tmp0 + tmp1;
            tmp11 = tmp0 - tmp1;
            tmp12 = tmp0 + tmp2;
            tmp13 = tmp0 - tmp2;
            z1 = (int)workspace[wp + 2];
            z2 = (int)workspace[wp + 6];
            z3 = z1 - z2;
            z4 = ((z3) * (2260));
            z3 = ((z3) * (11363));
            tmp0 = z3 + ((z2) * (20995));
            tmp1 = z4 + ((z1) * (7373));
            tmp2 = z3 - ((z1) * (4926));
            tmp3 = z4 - ((z2) * (4176));
            tmp20 = tmp10 + tmp0;
            tmp27 = tmp10 - tmp0;
            tmp21 = tmp12 + tmp1;
            tmp26 = tmp12 - tmp1;
            tmp22 = tmp13 + tmp2;
            tmp25 = tmp13 - tmp2;
            tmp23 = tmp11 + tmp3;
            tmp24 = tmp11 - tmp3;
            z1 = (int)workspace[wp + 1];
            z2 = (int)workspace[wp + 3];
            z3 = (int)workspace[wp + 5];
            z4 = (int)workspace[wp + 7];
            tmp11 = z1 + z3;
            tmp1  = ((z1 + z2) * (11086));
            tmp2  = ((tmp11) * (10217));
            tmp3  = ((z1 + z4) * (8956));
            tmp10 = ((z1 - z4) * (7350));
            tmp11 = ((tmp11) * (5461));
            tmp12 = ((z1 - z2) * (3363));
            tmp0  = tmp1 + tmp2 + tmp3 -
                    ((z1) * (18730));
            tmp13 = tmp10 + tmp11 + tmp12 -
                    ((z1) * (15038));
            z1    = ((z2 + z3) * (1136));
            tmp1  += z1 + ((z2) * (589));
            tmp2  += z1 - ((z3) * (9222));
            z1    = ((z3 - z2) * (11529));
            tmp11 += z1 - ((z3) * (6278));
            tmp12 += z1 + ((z2) * (16154));
            z2    += z4;
            z1    = ((z2) * (-5461));
            tmp1  += z1;
            tmp3  += z1 + ((z4) * (8728));
            z2    = ((z2) * (-10217));
            tmp10 += z2 + ((z4) * (25733));
            tmp12 += z2;
            z2    = ((z3 + z4) * (-11086));
            tmp2  += z2;
            tmp3  += z2;
            z2    = ((z4 - z3) * (3363));
            tmp10 += z2;
            tmp11 += z2;
            outp[op + 0]  = rl[(int)((tmp20 + tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 15] = rl[(int)((tmp20 - tmp0) >> (13 + P1 + 3)) & mask];
            outp[op + 1]  = rl[(int)((tmp21 + tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 14] = rl[(int)((tmp21 - tmp1) >> (13 + P1 + 3)) & mask];
            outp[op + 2]  = rl[(int)((tmp22 + tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 13] = rl[(int)((tmp22 - tmp2) >> (13 + P1 + 3)) & mask];
            outp[op + 3]  = rl[(int)((tmp23 + tmp3) >> (13 + P1 + 3)) & mask];
            outp[op + 12] = rl[(int)((tmp23 - tmp3) >> (13 + P1 + 3)) & mask];
            outp[op + 4]  = rl[(int)((tmp24 + tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 11] = rl[(int)((tmp24 - tmp10) >> (13 + P1 + 3)) & mask];
            outp[op + 5]  = rl[(int)((tmp25 + tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 10] = rl[(int)((tmp25 - tmp11) >> (13 + P1 + 3)) & mask];
            outp[op + 6]  = rl[(int)((tmp26 + tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 9]  = rl[(int)((tmp26 - tmp12) >> (13 + P1 + 3)) & mask];
            outp[op + 7]  = rl[(int)((tmp27 + tmp13) >> (13 + P1 + 3)) & mask];
            outp[op + 8]  = rl[(int)((tmp27 - tmp13) >> (13 + P1 + 3)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct4x4(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp2, tmp10, tmp12;
          int z1, z2, z3, z4;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 4];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 8; ctr > 0; ip++, qp++, wp++, ctr--) {
            if (ctr == 8 - 4)
              continue;
            if (coef[ip + 8 * 1] == 0 && coef[ip + 8 * 2] == 0 &&
                coef[ip + 8 * 3] == 0 && coef[ip + 8 * 5] == 0 &&
                coef[ip + 8 * 6] == 0 && coef[ip + 8 * 7] == 0) {
              int dcval = ((int)((uint)(((coef[ip + 8 * 0]) * (q[qp + 8 * 0]))) << (P1)));
              workspace[wp + 8 * 0] = dcval;
              workspace[wp + 8 * 1] = dcval;
              workspace[wp + 8 * 2] = dcval;
              workspace[wp + 8 * 3] = dcval;
              continue;
            }
            tmp0 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp0 = ((int)((uint)(tmp0) << (13 + 1)));
            z2 = ((coef[ip + 8 * 2]) * (q[qp + 8 * 2]));
            z3 = ((coef[ip + 8 * 6]) * (q[qp + 8 * 6]));
            tmp2 = ((z2) * (15137)) + ((z3) * (-6270));
            tmp10 = tmp0 + tmp2;
            tmp12 = tmp0 - tmp2;
            z1 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            z2 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            z3 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            z4 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            tmp0 = ((z1) * (-1730)) +
                   ((z2) * (11893)) +
                   ((z3) * (-17799)) +
                   ((z4) * (8697));
            tmp2 = ((z1) * (-4176)) +
                   ((z2) * (-4926)) +
                   ((z3) * (7373)) +
                   ((z4) * (20995));
            workspace[wp + 8 * 0] =
              (int)(((tmp10 + tmp2) + (1 << ((13 - P1 + 1) - 1))) >> (13 - P1 + 1));
            workspace[wp + 8 * 3] =
              (int)(((tmp10 - tmp2) + (1 << ((13 - P1 + 1) - 1))) >> (13 - P1 + 1));
            workspace[wp + 8 * 1] =
              (int)(((tmp12 + tmp0) + (1 << ((13 - P1 + 1) - 1))) >> (13 - P1 + 1));
            workspace[wp + 8 * 2] =
              (int)(((tmp12 - tmp0) + (1 << ((13 - P1 + 1) - 1))) >> (13 - P1 + 1));
          }
          wp = 0;
          for (ctr = 0; ctr < 4; ctr++) {
            op = (ctr) * stride;
            if (workspace[wp + 1] == 0 && workspace[wp + 2] == 0 && workspace[wp + 3] == 0 &&
                workspace[wp + 5] == 0 && workspace[wp + 6] == 0 && workspace[wp + 7] == 0) {
              int dcval = rl[(int)((((int)workspace[wp + 0]) + (1 << ((P1 + 3) - 1))) >> (P1 + 3)) & mask];
              outp[op + 0] = dcval;
              outp[op + 1] = dcval;
              outp[op + 2] = dcval;
              outp[op + 3] = dcval;
              wp += 8;
              continue;
            }
            tmp0 = ((int)((uint)((int)workspace[wp + 0]) << (13 + 1)));
            tmp2 = (((int)workspace[wp + 2]) * (15137)) +
                   (((int)workspace[wp + 6]) * (-6270));
            tmp10 = tmp0 + tmp2;
            tmp12 = tmp0 - tmp2;
            z1 = (int)workspace[wp + 7];
            z2 = (int)workspace[wp + 5];
            z3 = (int)workspace[wp + 3];
            z4 = (int)workspace[wp + 1];
            tmp0 = ((z1) * (-1730)) +
                   ((z2) * (11893)) +
                   ((z3) * (-17799)) +
                   ((z4) * (8697));
            tmp2 = ((z1) * (-4176)) +
                   ((z2) * (-4926)) +
                   ((z3) * (7373)) +
                   ((z4) * (20995));
            outp[op + 0] = rl[(int)(((tmp10 + tmp2) + (1 << ((13 + P1 + 3 + 1) - 1))) >> (13 + P1 + 3 + 1)) & mask];
            outp[op + 3] = rl[(int)(((tmp10 - tmp2) + (1 << ((13 + P1 + 3 + 1) - 1))) >> (13 + P1 + 3 + 1)) & mask];
            outp[op + 1] = rl[(int)(((tmp12 + tmp0) + (1 << ((13 + P1 + 3 + 1) - 1))) >> (13 + P1 + 3 + 1)) & mask];
            outp[op + 2] = rl[(int)(((tmp12 - tmp0) + (1 << ((13 + P1 + 3 + 1) - 1))) >> (13 + P1 + 3 + 1)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct2x2(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp10, z1;
          int ctr;
          Span<int> workspace = stackalloc int[8 * 2];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 8; ctr > 0; ip++, qp++, wp++, ctr--) {
            if (ctr == 8 - 2 || ctr == 8 - 4 || ctr == 8 - 6)
              continue;
            if (coef[ip + 8 * 1] == 0 && coef[ip + 8 * 3] == 0 &&
                coef[ip + 8 * 5] == 0 && coef[ip + 8 * 7] == 0) {
              int dcval = ((int)((uint)(((coef[ip + 8 * 0]) * (q[qp + 8 * 0]))) << (P1)));
              workspace[wp + 8 * 0] = dcval;
              workspace[wp + 8 * 1] = dcval;
              continue;
            }
            z1 = ((coef[ip + 8 * 0]) * (q[qp + 8 * 0]));
            tmp10 = ((int)((uint)(z1) << (13 + 2)));
            z1 = ((coef[ip + 8 * 7]) * (q[qp + 8 * 7]));
            tmp0 = ((z1) * (-5906));
            z1 = ((coef[ip + 8 * 5]) * (q[qp + 8 * 5]));
            tmp0 += ((z1) * (6967));
            z1 = ((coef[ip + 8 * 3]) * (q[qp + 8 * 3]));
            tmp0 += ((z1) * (-10426));
            z1 = ((coef[ip + 8 * 1]) * (q[qp + 8 * 1]));
            tmp0 += ((z1) * (29692));
            workspace[wp + 8 * 0] =
              (int)(((tmp10 + tmp0) + (1 << ((13 - P1 + 2) - 1))) >> (13 - P1 + 2));
            workspace[wp + 8 * 1] =
              (int)(((tmp10 - tmp0) + (1 << ((13 - P1 + 2) - 1))) >> (13 - P1 + 2));
          }
          wp = 0;
          for (ctr = 0; ctr < 2; ctr++) {
            op = (ctr) * stride;
            if (workspace[wp + 1] == 0 && workspace[wp + 3] == 0 && workspace[wp + 5] == 0 && workspace[wp + 7] == 0) {
              int dcval = rl[(int)((((int)workspace[wp + 0]) + (1 << ((P1 + 3) - 1))) >> (P1 + 3)) & mask];
              outp[op + 0] = dcval;
              outp[op + 1] = dcval;
              wp += 8;
              continue;
            }
            tmp10 = ((int)((uint)((int)workspace[wp + 0]) << (13 + 2)));
            tmp0 = (((int)workspace[wp + 7]) * (-5906)) +
                   (((int)workspace[wp + 5]) * (6967)) +
                   (((int)workspace[wp + 3]) * (-10426)) +
                   (((int)workspace[wp + 1]) * (29692));
            outp[op + 0] = rl[(int)(((tmp10 + tmp0) + (1 << ((13 + P1 + 3 + 2) - 1))) >> (13 + P1 + 3 + 2)) & mask];
            outp[op + 1] = rl[(int)(((tmp10 - tmp0) + (1 << ((13 + P1 + 3 + 2) - 1))) >> (13 + P1 + 3 + 2)) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdct1x1(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int dcval;
          qp = 0;
          dcval = ((coef[0]) * (q[qp + 0]));
          dcval = (int)((((int)dcval) + (1 << ((3) - 1))) >> (3));
          outp[(0) * stride] = rl[dcval & mask];
        }
    }

    private static void LjIdctIfast(ReadOnlySpan<short> coef, ReadOnlySpan<int> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          int tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6, tmp7;
          int tmp10, tmp11, tmp12, tmp13;
          int z5, z10, z11, z12, z13;
          int ctr;
          Span<int> workspace = stackalloc int[64];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 8; ctr > 0; ctr--) {
            if (coef[ip + 8 * 1] == 0 && coef[ip + 8 * 2] == 0 &&
                coef[ip + 8 * 3] == 0 && coef[ip + 8 * 4] == 0 &&
                coef[ip + 8 * 5] == 0 && coef[ip + 8 * 6] == 0 &&
                coef[ip + 8 * 7] == 0) {
              int dcval = (int)Dq(coef[ip + 8 * 0], q[qp + 8 * 0], P1);
              workspace[wp + 8 * 0] = dcval;
              workspace[wp + 8 * 1] = dcval;
              workspace[wp + 8 * 2] = dcval;
              workspace[wp + 8 * 3] = dcval;
              workspace[wp + 8 * 4] = dcval;
              workspace[wp + 8 * 5] = dcval;
              workspace[wp + 8 * 6] = dcval;
              workspace[wp + 8 * 7] = dcval;
              ip++;
              qp++;
              wp++;
              continue;
            }
            tmp0 = Dq(coef[ip + 8 * 0], q[qp + 8 * 0], P1);
            tmp1 = Dq(coef[ip + 8 * 2], q[qp + 8 * 2], P1);
            tmp2 = Dq(coef[ip + 8 * 4], q[qp + 8 * 4], P1);
            tmp3 = Dq(coef[ip + 8 * 6], q[qp + 8 * 6], P1);
            tmp10 = tmp0 + tmp2;
            tmp11 = tmp0 - tmp2;
            tmp13 = tmp1 + tmp3;
            tmp12 = ((int)((tmp1 - tmp3) * (362) >> 8)) - tmp13;
            tmp0 = tmp10 + tmp13;
            tmp3 = tmp10 - tmp13;
            tmp1 = tmp11 + tmp12;
            tmp2 = tmp11 - tmp12;
            tmp4 = Dq(coef[ip + 8 * 1], q[qp + 8 * 1], P1);
            tmp5 = Dq(coef[ip + 8 * 3], q[qp + 8 * 3], P1);
            tmp6 = Dq(coef[ip + 8 * 5], q[qp + 8 * 5], P1);
            tmp7 = Dq(coef[ip + 8 * 7], q[qp + 8 * 7], P1);
            z13 = tmp6 + tmp5;
            z10 = tmp6 - tmp5;
            z11 = tmp4 + tmp7;
            z12 = tmp4 - tmp7;
            tmp7 = z11 + z13;
            tmp11 = ((int)((z11 - z13) * (362) >> 8));
            z5 = ((int)((z10 + z12) * (473) >> 8));
            tmp10 = ((int)((z12) * (277) >> 8)) - z5;
            tmp12 = ((int)((z10) * (-669) >> 8)) + z5;
            tmp6 = tmp12 - tmp7;
            tmp5 = tmp11 - tmp6;
            tmp4 = tmp10 + tmp5;
            workspace[wp + 8 * 0] = (int)(tmp0 + tmp7);
            workspace[wp + 8 * 7] = (int)(tmp0 - tmp7);
            workspace[wp + 8 * 1] = (int)(tmp1 + tmp6);
            workspace[wp + 8 * 6] = (int)(tmp1 - tmp6);
            workspace[wp + 8 * 2] = (int)(tmp2 + tmp5);
            workspace[wp + 8 * 5] = (int)(tmp2 - tmp5);
            workspace[wp + 8 * 4] = (int)(tmp3 + tmp4);
            workspace[wp + 8 * 3] = (int)(tmp3 - tmp4);
            ip++;
            qp++;
            wp++;
          }
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++) {
            op = (ctr) * stride;
            if (workspace[wp + 1] == 0 && workspace[wp + 2] == 0 && workspace[wp + 3] == 0 && workspace[wp + 4] == 0 &&
                workspace[wp + 5] == 0 && workspace[wp + 6] == 0 && workspace[wp + 7] == 0) {
              int dcval =
                rl[((int)((workspace[wp + 0]) >> (P1 + 3))) & mask];
              outp[op + 0] = dcval;
              outp[op + 1] = dcval;
              outp[op + 2] = dcval;
              outp[op + 3] = dcval;
              outp[op + 4] = dcval;
              outp[op + 5] = dcval;
              outp[op + 6] = dcval;
              outp[op + 7] = dcval;
              wp += 8;
              continue;
            }
            tmp10 = ((int)workspace[wp + 0] + (int)workspace[wp + 4]);
            tmp11 = ((int)workspace[wp + 0] - (int)workspace[wp + 4]);
            tmp13 = ((int)workspace[wp + 2] + (int)workspace[wp + 6]);
            tmp12 =
              ((int)(((int)workspace[wp + 2] - (int)workspace[wp + 6]) * (362) >> 8)) - tmp13;
            tmp0 = tmp10 + tmp13;
            tmp3 = tmp10 - tmp13;
            tmp1 = tmp11 + tmp12;
            tmp2 = tmp11 - tmp12;
            z13 = (int)workspace[wp + 5] + (int)workspace[wp + 3];
            z10 = (int)workspace[wp + 5] - (int)workspace[wp + 3];
            z11 = (int)workspace[wp + 1] + (int)workspace[wp + 7];
            z12 = (int)workspace[wp + 1] - (int)workspace[wp + 7];
            tmp7 = z11 + z13;
            tmp11 = ((int)((z11 - z13) * (362) >> 8));
            z5 = ((int)((z10 + z12) * (473) >> 8));
            tmp10 = ((int)((z12) * (277) >> 8)) - z5;
            tmp12 = ((int)((z10) * (-669) >> 8)) + z5;
            tmp6 = tmp12 - tmp7;
            tmp5 = tmp11 - tmp6;
            tmp4 = tmp10 + tmp5;
            outp[op + 0] =
              rl[((int)((tmp0 + tmp7) >> (P1 + 3))) & mask];
            outp[op + 7] =
              rl[((int)((tmp0 - tmp7) >> (P1 + 3))) & mask];
            outp[op + 1] =
              rl[((int)((tmp1 + tmp6) >> (P1 + 3))) & mask];
            outp[op + 6] =
              rl[((int)((tmp1 - tmp6) >> (P1 + 3))) & mask];
            outp[op + 2] =
              rl[((int)((tmp2 + tmp5) >> (P1 + 3))) & mask];
            outp[op + 5] =
              rl[((int)((tmp2 - tmp5) >> (P1 + 3))) & mask];
            outp[op + 4] =
              rl[((int)((tmp3 + tmp4) >> (P1 + 3))) & mask];
            outp[op + 3] =
              rl[((int)((tmp3 - tmp4) >> (P1 + 3))) & mask];
            wp += 8;
          }
        }
    }

    private static void LjIdctFloat(ReadOnlySpan<short> coef, ReadOnlySpan<float> q, Span<int> outp, int stride, int[] rl, int mask, int P1, int center)
    {
        int ip = 0, qp = 0, wp = 0, op = 0;
        unchecked
        {
          float tmp0, tmp1, tmp2, tmp3, tmp4, tmp5, tmp6, tmp7;
          float tmp10, tmp11, tmp12, tmp13;
          float z5, z10, z11, z12, z13;
          int ctr;
          Span<float> workspace = stackalloc float[64];
          ip = 0;
          qp = 0;
          wp = 0;
          for (ctr = 8; ctr > 0; ctr--) {
            if (coef[ip + 8 * 1] == 0 && coef[ip + 8 * 2] == 0 &&
                coef[ip + 8 * 3] == 0 && coef[ip + 8 * 4] == 0 &&
                coef[ip + 8 * 5] == 0 && coef[ip + 8 * 6] == 0 &&
                coef[ip + 8 * 7] == 0) {
              float dcval = ((float)(coef[ip + 8 * 0]) * (q[qp + 8 * 0] * 0.125f));
              workspace[wp + 8 * 0] = dcval;
              workspace[wp + 8 * 1] = dcval;
              workspace[wp + 8 * 2] = dcval;
              workspace[wp + 8 * 3] = dcval;
              workspace[wp + 8 * 4] = dcval;
              workspace[wp + 8 * 5] = dcval;
              workspace[wp + 8 * 6] = dcval;
              workspace[wp + 8 * 7] = dcval;
              ip++;
              qp++;
              wp++;
              continue;
            }
            tmp0 = ((float)(coef[ip + 8 * 0]) * (q[qp + 8 * 0] * 0.125f));
            tmp1 = ((float)(coef[ip + 8 * 2]) * (q[qp + 8 * 2] * 0.125f));
            tmp2 = ((float)(coef[ip + 8 * 4]) * (q[qp + 8 * 4] * 0.125f));
            tmp3 = ((float)(coef[ip + 8 * 6]) * (q[qp + 8 * 6] * 0.125f));
            tmp10 = tmp0 + tmp2;
            tmp11 = tmp0 - tmp2;
            tmp13 = tmp1 + tmp3;
            tmp12 = (tmp1 - tmp3) * (1.414213562f) - tmp13;
            tmp0 = tmp10 + tmp13;
            tmp3 = tmp10 - tmp13;
            tmp1 = tmp11 + tmp12;
            tmp2 = tmp11 - tmp12;
            tmp4 = ((float)(coef[ip + 8 * 1]) * (q[qp + 8 * 1] * 0.125f));
            tmp5 = ((float)(coef[ip + 8 * 3]) * (q[qp + 8 * 3] * 0.125f));
            tmp6 = ((float)(coef[ip + 8 * 5]) * (q[qp + 8 * 5] * 0.125f));
            tmp7 = ((float)(coef[ip + 8 * 7]) * (q[qp + 8 * 7] * 0.125f));
            z13 = tmp6 + tmp5;
            z10 = tmp6 - tmp5;
            z11 = tmp4 + tmp7;
            z12 = tmp4 - tmp7;
            tmp7 = z11 + z13;
            tmp11 = (z11 - z13) * (1.414213562f);
            z5 = (z10 + z12) * (1.847759065f);
            tmp10 = z5 - z12 * (1.082392200f);
            tmp12 = z5 - z10 * (2.613125930f);
            tmp6 = tmp12 - tmp7;
            tmp5 = tmp11 - tmp6;
            tmp4 = tmp10 - tmp5;
            workspace[wp + 8 * 0] = tmp0 + tmp7;
            workspace[wp + 8 * 7] = tmp0 - tmp7;
            workspace[wp + 8 * 1] = tmp1 + tmp6;
            workspace[wp + 8 * 6] = tmp1 - tmp6;
            workspace[wp + 8 * 2] = tmp2 + tmp5;
            workspace[wp + 8 * 5] = tmp2 - tmp5;
            workspace[wp + 8 * 3] = tmp3 + tmp4;
            workspace[wp + 8 * 4] = tmp3 - tmp4;
            ip++;
            qp++;
            wp++;
          }
          wp = 0;
          for (ctr = 0; ctr < 8; ctr++) {
            op = (ctr) * stride;
            z5 = workspace[wp + 0] + ((float)center + 0.5f);
            tmp10 = z5 + workspace[wp + 4];
            tmp11 = z5 - workspace[wp + 4];
            tmp13 = workspace[wp + 2] + workspace[wp + 6];
            tmp12 = (workspace[wp + 2] - workspace[wp + 6]) * (1.414213562f) - tmp13;
            tmp0 = tmp10 + tmp13;
            tmp3 = tmp10 - tmp13;
            tmp1 = tmp11 + tmp12;
            tmp2 = tmp11 - tmp12;
            z13 = workspace[wp + 5] + workspace[wp + 3];
            z10 = workspace[wp + 5] - workspace[wp + 3];
            z11 = workspace[wp + 1] + workspace[wp + 7];
            z12 = workspace[wp + 1] - workspace[wp + 7];
            tmp7 = z11 + z13;
            tmp11 = (z11 - z13) * (1.414213562f);
            z5 = (z10 + z12) * (1.847759065f);
            tmp10 = z5 - z12 * (1.082392200f);
            tmp12 = z5 - z10 * (2.613125930f);
            tmp6 = tmp12 - tmp7;
            tmp5 = tmp11 - tmp6;
            tmp4 = tmp10 - tmp5;
            outp[op + 0] = rl[(F2I(tmp0 + tmp7)) & mask];
            outp[op + 7] = rl[(F2I(tmp0 - tmp7)) & mask];
            outp[op + 1] = rl[(F2I(tmp1 + tmp6)) & mask];
            outp[op + 6] = rl[(F2I(tmp1 - tmp6)) & mask];
            outp[op + 2] = rl[(F2I(tmp2 + tmp5)) & mask];
            outp[op + 5] = rl[(F2I(tmp2 - tmp5)) & mask];
            outp[op + 3] = rl[(F2I(tmp3 + tmp4)) & mask];
            outp[op + 4] = rl[(F2I(tmp3 - tmp4)) & mask];
            wp += 8;
          }
        }
    }

    // jidctfst.c DEQUANTIZE: a plain product at 8 bits; at 12 bits the multipliers carry IFAST_SCALE_BITS = 13.
    private static int Dq(int coef, int q, int p1) => p1 == 2 ? coef * q : (coef * q) >> (13 - p1);

    // (int) of a float as x86 C code computes it (cvttss2si: INT_MIN for NaN / out of range).
    private static int F2I(float f) => f >= -2147483648f && f < 2147483648f ? (int)f : int.MinValue;
}
