// <auto-generated> by tools/codegen/gen_fwdtx.py from libaom 3.14.1 (av1/encoder/av1_fwd_txfm1d.c, av1_fwd_txfm2d.c,
// av1/common/av1_txfm.c): libaom's integer forward transform, 8 rows / columns per Vector256<int>. Do not edit by hand.
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;
using V = System.Runtime.Intrinsics.Vector256<int>;

namespace SharpImage.Formats.Av1;

[SkipLocalsInit]
internal static partial class Av1FwdTxfmAom
{
    private static readonly int[] CosPiData = { 1024, 1024, 1023, 1021, 1019, 1016, 1013, 1009, 1004, 999, 993, 987, 980, 972, 964, 955, 946, 936, 926, 915, 903, 891, 878, 865, 851, 837, 822, 807, 792, 775, 759, 742, 724, 706, 688, 669, 650, 630, 610, 590, 569, 548, 526, 505, 483, 460, 438, 415, 392, 369, 345, 321, 297, 273, 249, 224, 200, 175, 150, 125, 100, 75, 50, 25, 2048, 2047, 2046, 2042, 2038, 2033, 2026, 2018, 2009, 1998, 1987, 1974, 1960, 1945, 1928, 1911, 1892, 1872, 1851, 1829, 1806, 1782, 1757, 1730, 1703, 1674, 1645, 1615, 1583, 1551, 1517, 1483, 1448, 1412, 1375, 1338, 1299, 1260, 1220, 1179, 1138, 1096, 1053, 1009, 965, 921, 876, 830, 784, 737, 690, 642, 595, 546, 498, 449, 400, 350, 301, 251, 201, 151, 100, 50, 4096, 4095, 4091, 4085, 4076, 4065, 4052, 4036, 4017, 3996, 3973, 3948, 3920, 3889, 3857, 3822, 3784, 3745, 3703, 3659, 3612, 3564, 3513, 3461, 3406, 3349, 3290, 3229, 3166, 3102, 3035, 2967, 2896, 2824, 2751, 2675, 2598, 2520, 2440, 2359, 2276, 2191, 2106, 2019, 1931, 1842, 1751, 1660, 1567, 1474, 1380, 1285, 1189, 1092, 995, 897, 799, 700, 601, 501, 401, 301, 201, 101, 8192, 8190, 8182, 8170, 8153, 8130, 8103, 8071, 8035, 7993, 7946, 7895, 7839, 7779, 7713, 7643, 7568, 7489, 7405, 7317, 7225, 7128, 7027, 6921, 6811, 6698, 6580, 6458, 6333, 6203, 6070, 5933, 5793, 5649, 5501, 5351, 5197, 5040, 4880, 4717, 4551, 4383, 4212, 4038, 3862, 3683, 3503, 3320, 3135, 2948, 2760, 2570, 2378, 2185, 1990, 1795, 1598, 1401, 1202, 1003, 803, 603, 402, 201 };
    private static readonly int[] SinPiData = { 0, 330, 621, 836, 951, 0, 660, 1241, 1672, 1901, 0, 1321, 2482, 3344, 3803, 0, 2642, 4964, 6689, 7606 };
    private static ReadOnlySpan<int> CosPi(int cosBit) => CosPiData.AsSpan((cosBit - 10) * 64, 64);
    private static ReadOnlySpan<int> SinPi(int cosBit) => SinPiData.AsSpan((cosBit - 10) * 5, 5);

    // half_btf: round_shift(w0 * in0 + w1 * in1, bit), in 32 bits as libaom's AVX2 does (its stage ranges keep it exact)
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static V Hb(int w0, V in0, int w1, V in1, int bit)
        => Vector256.ShiftRightArithmetic(Vector256.Create(w0) * in0 + Vector256.Create(w1) * in1 + Vector256.Create(1 << (bit - 1)), bit);

    // round_shift((int64)x * m, bit) exactly (64-bit product through doubles: |x * m| < 2^53)
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static V MulRound(V x, int m, int bit)
    {
        if (!Avx.IsSupported) return MulRoundScalar(x, m, bit);
        var dm = Vector256.Create((double)m); var r = Vector256.Create((double)(1 << (bit - 1))); var inv = Vector256.Create(1.0 / (1 << bit));
        var lo = Vector256.Floor((Avx.ConvertToVector256Double(x.GetLower()) * dm + r) * inv);
        var hi = Vector256.Floor((Avx.ConvertToVector256Double(x.GetUpper()) * dm + r) * inv);
        return Vector256.Create(Avx.ConvertToVector128Int32WithTruncation(lo), Avx.ConvertToVector128Int32WithTruncation(hi));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static V MulRoundScalar(V x, int m, int bit)
    {
        long r = 1L << (bit - 1);
        Unsafe.SkipInit(out V res);
        for (int i = 0; i < 8; i++) Unsafe.Add(ref Unsafe.As<V, int>(ref res), i) = (int)(((long)x.GetElement(i) * m + r) >> bit);
        return res;
    }

    private static void Fdct4(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x3 = Unsafe.Add(ref input, 3);
        V t0 = x0 + x3;
        V x1 = Unsafe.Add(ref input, 1);
        V x2 = Unsafe.Add(ref input, 2);
        V t1 = x1 + x2;
        V t2 = -x2 + x1;
        V t3 = -x3 + x0;
        V t4 = Hb(Unsafe.Add(ref cp, 32), t0, Unsafe.Add(ref cp, 32), t1, cosBit);
        V t5 = Hb(-Unsafe.Add(ref cp, 32), t1, Unsafe.Add(ref cp, 32), t0, cosBit);
        V t6 = Hb(Unsafe.Add(ref cp, 48), t2, Unsafe.Add(ref cp, 16), t3, cosBit);
        V t7 = Hb(Unsafe.Add(ref cp, 48), t3, -Unsafe.Add(ref cp, 16), t2, cosBit);
        Unsafe.Add(ref output, 0) = t4;
        Unsafe.Add(ref output, 1) = t6;
        Unsafe.Add(ref output, 2) = t5;
        Unsafe.Add(ref output, 3) = t7;
    }

    private static void Fdct8(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x7 = Unsafe.Add(ref input, 7);
        V t0 = x0 + x7;
        V x1 = Unsafe.Add(ref input, 1);
        V x6 = Unsafe.Add(ref input, 6);
        V t1 = x1 + x6;
        V x2 = Unsafe.Add(ref input, 2);
        V x5 = Unsafe.Add(ref input, 5);
        V t2 = x2 + x5;
        V x3 = Unsafe.Add(ref input, 3);
        V x4 = Unsafe.Add(ref input, 4);
        V t3 = x3 + x4;
        V t4 = -x4 + x3;
        V t5 = -x5 + x2;
        V t6 = -x6 + x1;
        V t7 = -x7 + x0;
        V t8 = t0 + t3;
        V t9 = t1 + t2;
        V t10 = -t2 + t1;
        V t11 = -t3 + t0;
        V t12 = Hb(-Unsafe.Add(ref cp, 32), t5, Unsafe.Add(ref cp, 32), t6, cosBit);
        V t13 = Hb(Unsafe.Add(ref cp, 32), t6, Unsafe.Add(ref cp, 32), t5, cosBit);
        V t14 = Hb(Unsafe.Add(ref cp, 32), t8, Unsafe.Add(ref cp, 32), t9, cosBit);
        V t15 = Hb(-Unsafe.Add(ref cp, 32), t9, Unsafe.Add(ref cp, 32), t8, cosBit);
        V t16 = Hb(Unsafe.Add(ref cp, 48), t10, Unsafe.Add(ref cp, 16), t11, cosBit);
        V t17 = Hb(Unsafe.Add(ref cp, 48), t11, -Unsafe.Add(ref cp, 16), t10, cosBit);
        V t18 = t4 + t12;
        V t19 = -t12 + t4;
        V t20 = -t13 + t7;
        V t21 = t7 + t13;
        V t22 = Hb(Unsafe.Add(ref cp, 56), t18, Unsafe.Add(ref cp, 8), t21, cosBit);
        V t23 = Hb(Unsafe.Add(ref cp, 24), t19, Unsafe.Add(ref cp, 40), t20, cosBit);
        V t24 = Hb(Unsafe.Add(ref cp, 24), t20, -Unsafe.Add(ref cp, 40), t19, cosBit);
        V t25 = Hb(Unsafe.Add(ref cp, 56), t21, -Unsafe.Add(ref cp, 8), t18, cosBit);
        Unsafe.Add(ref output, 0) = t14;
        Unsafe.Add(ref output, 1) = t22;
        Unsafe.Add(ref output, 2) = t16;
        Unsafe.Add(ref output, 3) = t24;
        Unsafe.Add(ref output, 4) = t15;
        Unsafe.Add(ref output, 5) = t23;
        Unsafe.Add(ref output, 6) = t17;
        Unsafe.Add(ref output, 7) = t25;
    }

    private static void Fdct16(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x15 = Unsafe.Add(ref input, 15);
        V t0 = x0 + x15;
        V x1 = Unsafe.Add(ref input, 1);
        V x14 = Unsafe.Add(ref input, 14);
        V t1 = x1 + x14;
        V x2 = Unsafe.Add(ref input, 2);
        V x13 = Unsafe.Add(ref input, 13);
        V t2 = x2 + x13;
        V x3 = Unsafe.Add(ref input, 3);
        V x12 = Unsafe.Add(ref input, 12);
        V t3 = x3 + x12;
        V x4 = Unsafe.Add(ref input, 4);
        V x11 = Unsafe.Add(ref input, 11);
        V t4 = x4 + x11;
        V x5 = Unsafe.Add(ref input, 5);
        V x10 = Unsafe.Add(ref input, 10);
        V t5 = x5 + x10;
        V x6 = Unsafe.Add(ref input, 6);
        V x9 = Unsafe.Add(ref input, 9);
        V t6 = x6 + x9;
        V x7 = Unsafe.Add(ref input, 7);
        V x8 = Unsafe.Add(ref input, 8);
        V t7 = x7 + x8;
        V t8 = -x8 + x7;
        V t9 = -x9 + x6;
        V t10 = -x10 + x5;
        V t11 = -x11 + x4;
        V t12 = -x12 + x3;
        V t13 = -x13 + x2;
        V t14 = -x14 + x1;
        V t15 = -x15 + x0;
        V t16 = t0 + t7;
        V t17 = t1 + t6;
        V t18 = t2 + t5;
        V t19 = t3 + t4;
        V t20 = -t4 + t3;
        V t21 = -t5 + t2;
        V t22 = -t6 + t1;
        V t23 = -t7 + t0;
        V t24 = Hb(-Unsafe.Add(ref cp, 32), t10, Unsafe.Add(ref cp, 32), t13, cosBit);
        V t25 = Hb(-Unsafe.Add(ref cp, 32), t11, Unsafe.Add(ref cp, 32), t12, cosBit);
        V t26 = Hb(Unsafe.Add(ref cp, 32), t12, Unsafe.Add(ref cp, 32), t11, cosBit);
        V t27 = Hb(Unsafe.Add(ref cp, 32), t13, Unsafe.Add(ref cp, 32), t10, cosBit);
        V t28 = t16 + t19;
        V t29 = t17 + t18;
        V t30 = -t18 + t17;
        V t31 = -t19 + t16;
        V t32 = Hb(-Unsafe.Add(ref cp, 32), t21, Unsafe.Add(ref cp, 32), t22, cosBit);
        V t33 = Hb(Unsafe.Add(ref cp, 32), t22, Unsafe.Add(ref cp, 32), t21, cosBit);
        V t34 = t8 + t25;
        V t35 = t9 + t24;
        V t36 = -t24 + t9;
        V t37 = -t25 + t8;
        V t38 = -t26 + t15;
        V t39 = -t27 + t14;
        V t40 = t14 + t27;
        V t41 = t15 + t26;
        V t42 = Hb(Unsafe.Add(ref cp, 32), t28, Unsafe.Add(ref cp, 32), t29, cosBit);
        V t43 = Hb(-Unsafe.Add(ref cp, 32), t29, Unsafe.Add(ref cp, 32), t28, cosBit);
        V t44 = Hb(Unsafe.Add(ref cp, 48), t30, Unsafe.Add(ref cp, 16), t31, cosBit);
        V t45 = Hb(Unsafe.Add(ref cp, 48), t31, -Unsafe.Add(ref cp, 16), t30, cosBit);
        V t46 = t20 + t32;
        V t47 = -t32 + t20;
        V t48 = -t33 + t23;
        V t49 = t23 + t33;
        V t50 = Hb(-Unsafe.Add(ref cp, 16), t35, Unsafe.Add(ref cp, 48), t40, cosBit);
        V t51 = Hb(-Unsafe.Add(ref cp, 48), t36, -Unsafe.Add(ref cp, 16), t39, cosBit);
        V t52 = Hb(Unsafe.Add(ref cp, 48), t39, -Unsafe.Add(ref cp, 16), t36, cosBit);
        V t53 = Hb(Unsafe.Add(ref cp, 16), t40, Unsafe.Add(ref cp, 48), t35, cosBit);
        V t54 = Hb(Unsafe.Add(ref cp, 56), t46, Unsafe.Add(ref cp, 8), t49, cosBit);
        V t55 = Hb(Unsafe.Add(ref cp, 24), t47, Unsafe.Add(ref cp, 40), t48, cosBit);
        V t56 = Hb(Unsafe.Add(ref cp, 24), t48, -Unsafe.Add(ref cp, 40), t47, cosBit);
        V t57 = Hb(Unsafe.Add(ref cp, 56), t49, -Unsafe.Add(ref cp, 8), t46, cosBit);
        V t58 = t34 + t50;
        V t59 = -t50 + t34;
        V t60 = -t51 + t37;
        V t61 = t37 + t51;
        V t62 = t38 + t52;
        V t63 = -t52 + t38;
        V t64 = -t53 + t41;
        V t65 = t41 + t53;
        V t66 = Hb(Unsafe.Add(ref cp, 60), t58, Unsafe.Add(ref cp, 4), t65, cosBit);
        V t67 = Hb(Unsafe.Add(ref cp, 28), t59, Unsafe.Add(ref cp, 36), t64, cosBit);
        V t68 = Hb(Unsafe.Add(ref cp, 44), t60, Unsafe.Add(ref cp, 20), t63, cosBit);
        V t69 = Hb(Unsafe.Add(ref cp, 12), t61, Unsafe.Add(ref cp, 52), t62, cosBit);
        V t70 = Hb(Unsafe.Add(ref cp, 12), t62, -Unsafe.Add(ref cp, 52), t61, cosBit);
        V t71 = Hb(Unsafe.Add(ref cp, 44), t63, -Unsafe.Add(ref cp, 20), t60, cosBit);
        V t72 = Hb(Unsafe.Add(ref cp, 28), t64, -Unsafe.Add(ref cp, 36), t59, cosBit);
        V t73 = Hb(Unsafe.Add(ref cp, 60), t65, -Unsafe.Add(ref cp, 4), t58, cosBit);
        Unsafe.Add(ref output, 0) = t42;
        Unsafe.Add(ref output, 1) = t66;
        Unsafe.Add(ref output, 2) = t54;
        Unsafe.Add(ref output, 3) = t70;
        Unsafe.Add(ref output, 4) = t44;
        Unsafe.Add(ref output, 5) = t68;
        Unsafe.Add(ref output, 6) = t56;
        Unsafe.Add(ref output, 7) = t72;
        Unsafe.Add(ref output, 8) = t43;
        Unsafe.Add(ref output, 9) = t67;
        Unsafe.Add(ref output, 10) = t55;
        Unsafe.Add(ref output, 11) = t71;
        Unsafe.Add(ref output, 12) = t45;
        Unsafe.Add(ref output, 13) = t69;
        Unsafe.Add(ref output, 14) = t57;
        Unsafe.Add(ref output, 15) = t73;
    }

    private static void Fdct32(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x31 = Unsafe.Add(ref input, 31);
        V t0 = x0 + x31;
        V x1 = Unsafe.Add(ref input, 1);
        V x30 = Unsafe.Add(ref input, 30);
        V t1 = x1 + x30;
        V x2 = Unsafe.Add(ref input, 2);
        V x29 = Unsafe.Add(ref input, 29);
        V t2 = x2 + x29;
        V x3 = Unsafe.Add(ref input, 3);
        V x28 = Unsafe.Add(ref input, 28);
        V t3 = x3 + x28;
        V x4 = Unsafe.Add(ref input, 4);
        V x27 = Unsafe.Add(ref input, 27);
        V t4 = x4 + x27;
        V x5 = Unsafe.Add(ref input, 5);
        V x26 = Unsafe.Add(ref input, 26);
        V t5 = x5 + x26;
        V x6 = Unsafe.Add(ref input, 6);
        V x25 = Unsafe.Add(ref input, 25);
        V t6 = x6 + x25;
        V x7 = Unsafe.Add(ref input, 7);
        V x24 = Unsafe.Add(ref input, 24);
        V t7 = x7 + x24;
        V x8 = Unsafe.Add(ref input, 8);
        V x23 = Unsafe.Add(ref input, 23);
        V t8 = x8 + x23;
        V x9 = Unsafe.Add(ref input, 9);
        V x22 = Unsafe.Add(ref input, 22);
        V t9 = x9 + x22;
        V x10 = Unsafe.Add(ref input, 10);
        V x21 = Unsafe.Add(ref input, 21);
        V t10 = x10 + x21;
        V x11 = Unsafe.Add(ref input, 11);
        V x20 = Unsafe.Add(ref input, 20);
        V t11 = x11 + x20;
        V x12 = Unsafe.Add(ref input, 12);
        V x19 = Unsafe.Add(ref input, 19);
        V t12 = x12 + x19;
        V x13 = Unsafe.Add(ref input, 13);
        V x18 = Unsafe.Add(ref input, 18);
        V t13 = x13 + x18;
        V x14 = Unsafe.Add(ref input, 14);
        V x17 = Unsafe.Add(ref input, 17);
        V t14 = x14 + x17;
        V x15 = Unsafe.Add(ref input, 15);
        V x16 = Unsafe.Add(ref input, 16);
        V t15 = x15 + x16;
        V t16 = -x16 + x15;
        V t17 = -x17 + x14;
        V t18 = -x18 + x13;
        V t19 = -x19 + x12;
        V t20 = -x20 + x11;
        V t21 = -x21 + x10;
        V t22 = -x22 + x9;
        V t23 = -x23 + x8;
        V t24 = -x24 + x7;
        V t25 = -x25 + x6;
        V t26 = -x26 + x5;
        V t27 = -x27 + x4;
        V t28 = -x28 + x3;
        V t29 = -x29 + x2;
        V t30 = -x30 + x1;
        V t31 = -x31 + x0;
        V t32 = t0 + t15;
        V t33 = t1 + t14;
        V t34 = t2 + t13;
        V t35 = t3 + t12;
        V t36 = t4 + t11;
        V t37 = t5 + t10;
        V t38 = t6 + t9;
        V t39 = t7 + t8;
        V t40 = -t8 + t7;
        V t41 = -t9 + t6;
        V t42 = -t10 + t5;
        V t43 = -t11 + t4;
        V t44 = -t12 + t3;
        V t45 = -t13 + t2;
        V t46 = -t14 + t1;
        V t47 = -t15 + t0;
        V t48 = Hb(-Unsafe.Add(ref cp, 32), t20, Unsafe.Add(ref cp, 32), t27, cosBit);
        V t49 = Hb(-Unsafe.Add(ref cp, 32), t21, Unsafe.Add(ref cp, 32), t26, cosBit);
        V t50 = Hb(-Unsafe.Add(ref cp, 32), t22, Unsafe.Add(ref cp, 32), t25, cosBit);
        V t51 = Hb(-Unsafe.Add(ref cp, 32), t23, Unsafe.Add(ref cp, 32), t24, cosBit);
        V t52 = Hb(Unsafe.Add(ref cp, 32), t24, Unsafe.Add(ref cp, 32), t23, cosBit);
        V t53 = Hb(Unsafe.Add(ref cp, 32), t25, Unsafe.Add(ref cp, 32), t22, cosBit);
        V t54 = Hb(Unsafe.Add(ref cp, 32), t26, Unsafe.Add(ref cp, 32), t21, cosBit);
        V t55 = Hb(Unsafe.Add(ref cp, 32), t27, Unsafe.Add(ref cp, 32), t20, cosBit);
        V t56 = t32 + t39;
        V t57 = t33 + t38;
        V t58 = t34 + t37;
        V t59 = t35 + t36;
        V t60 = -t36 + t35;
        V t61 = -t37 + t34;
        V t62 = -t38 + t33;
        V t63 = -t39 + t32;
        V t64 = Hb(-Unsafe.Add(ref cp, 32), t42, Unsafe.Add(ref cp, 32), t45, cosBit);
        V t65 = Hb(-Unsafe.Add(ref cp, 32), t43, Unsafe.Add(ref cp, 32), t44, cosBit);
        V t66 = Hb(Unsafe.Add(ref cp, 32), t44, Unsafe.Add(ref cp, 32), t43, cosBit);
        V t67 = Hb(Unsafe.Add(ref cp, 32), t45, Unsafe.Add(ref cp, 32), t42, cosBit);
        V t68 = t16 + t51;
        V t69 = t17 + t50;
        V t70 = t18 + t49;
        V t71 = t19 + t48;
        V t72 = -t48 + t19;
        V t73 = -t49 + t18;
        V t74 = -t50 + t17;
        V t75 = -t51 + t16;
        V t76 = -t52 + t31;
        V t77 = -t53 + t30;
        V t78 = -t54 + t29;
        V t79 = -t55 + t28;
        V t80 = t28 + t55;
        V t81 = t29 + t54;
        V t82 = t30 + t53;
        V t83 = t31 + t52;
        V t84 = t56 + t59;
        V t85 = t57 + t58;
        V t86 = -t58 + t57;
        V t87 = -t59 + t56;
        V t88 = Hb(-Unsafe.Add(ref cp, 32), t61, Unsafe.Add(ref cp, 32), t62, cosBit);
        V t89 = Hb(Unsafe.Add(ref cp, 32), t62, Unsafe.Add(ref cp, 32), t61, cosBit);
        V t90 = t40 + t65;
        V t91 = t41 + t64;
        V t92 = -t64 + t41;
        V t93 = -t65 + t40;
        V t94 = -t66 + t47;
        V t95 = -t67 + t46;
        V t96 = t46 + t67;
        V t97 = t47 + t66;
        V t98 = Hb(-Unsafe.Add(ref cp, 16), t70, Unsafe.Add(ref cp, 48), t81, cosBit);
        V t99 = Hb(-Unsafe.Add(ref cp, 16), t71, Unsafe.Add(ref cp, 48), t80, cosBit);
        V t100 = Hb(-Unsafe.Add(ref cp, 48), t72, -Unsafe.Add(ref cp, 16), t79, cosBit);
        V t101 = Hb(-Unsafe.Add(ref cp, 48), t73, -Unsafe.Add(ref cp, 16), t78, cosBit);
        V t102 = Hb(Unsafe.Add(ref cp, 48), t78, -Unsafe.Add(ref cp, 16), t73, cosBit);
        V t103 = Hb(Unsafe.Add(ref cp, 48), t79, -Unsafe.Add(ref cp, 16), t72, cosBit);
        V t104 = Hb(Unsafe.Add(ref cp, 16), t80, Unsafe.Add(ref cp, 48), t71, cosBit);
        V t105 = Hb(Unsafe.Add(ref cp, 16), t81, Unsafe.Add(ref cp, 48), t70, cosBit);
        V t106 = Hb(Unsafe.Add(ref cp, 32), t84, Unsafe.Add(ref cp, 32), t85, cosBit);
        V t107 = Hb(-Unsafe.Add(ref cp, 32), t85, Unsafe.Add(ref cp, 32), t84, cosBit);
        V t108 = Hb(Unsafe.Add(ref cp, 48), t86, Unsafe.Add(ref cp, 16), t87, cosBit);
        V t109 = Hb(Unsafe.Add(ref cp, 48), t87, -Unsafe.Add(ref cp, 16), t86, cosBit);
        V t110 = t60 + t88;
        V t111 = -t88 + t60;
        V t112 = -t89 + t63;
        V t113 = t63 + t89;
        V t114 = Hb(-Unsafe.Add(ref cp, 16), t91, Unsafe.Add(ref cp, 48), t96, cosBit);
        V t115 = Hb(-Unsafe.Add(ref cp, 48), t92, -Unsafe.Add(ref cp, 16), t95, cosBit);
        V t116 = Hb(Unsafe.Add(ref cp, 48), t95, -Unsafe.Add(ref cp, 16), t92, cosBit);
        V t117 = Hb(Unsafe.Add(ref cp, 16), t96, Unsafe.Add(ref cp, 48), t91, cosBit);
        V t118 = t68 + t99;
        V t119 = t69 + t98;
        V t120 = -t98 + t69;
        V t121 = -t99 + t68;
        V t122 = -t100 + t75;
        V t123 = -t101 + t74;
        V t124 = t74 + t101;
        V t125 = t75 + t100;
        V t126 = t76 + t103;
        V t127 = t77 + t102;
        V t128 = -t102 + t77;
        V t129 = -t103 + t76;
        V t130 = -t104 + t83;
        V t131 = -t105 + t82;
        V t132 = t82 + t105;
        V t133 = t83 + t104;
        V t134 = Hb(Unsafe.Add(ref cp, 56), t110, Unsafe.Add(ref cp, 8), t113, cosBit);
        V t135 = Hb(Unsafe.Add(ref cp, 24), t111, Unsafe.Add(ref cp, 40), t112, cosBit);
        V t136 = Hb(Unsafe.Add(ref cp, 24), t112, -Unsafe.Add(ref cp, 40), t111, cosBit);
        V t137 = Hb(Unsafe.Add(ref cp, 56), t113, -Unsafe.Add(ref cp, 8), t110, cosBit);
        V t138 = t90 + t114;
        V t139 = -t114 + t90;
        V t140 = -t115 + t93;
        V t141 = t93 + t115;
        V t142 = t94 + t116;
        V t143 = -t116 + t94;
        V t144 = -t117 + t97;
        V t145 = t97 + t117;
        V t146 = Hb(-Unsafe.Add(ref cp, 8), t119, Unsafe.Add(ref cp, 56), t132, cosBit);
        V t147 = Hb(-Unsafe.Add(ref cp, 56), t120, -Unsafe.Add(ref cp, 8), t131, cosBit);
        V t148 = Hb(-Unsafe.Add(ref cp, 40), t123, Unsafe.Add(ref cp, 24), t128, cosBit);
        V t149 = Hb(-Unsafe.Add(ref cp, 24), t124, -Unsafe.Add(ref cp, 40), t127, cosBit);
        V t150 = Hb(Unsafe.Add(ref cp, 24), t127, -Unsafe.Add(ref cp, 40), t124, cosBit);
        V t151 = Hb(Unsafe.Add(ref cp, 40), t128, Unsafe.Add(ref cp, 24), t123, cosBit);
        V t152 = Hb(Unsafe.Add(ref cp, 56), t131, -Unsafe.Add(ref cp, 8), t120, cosBit);
        V t153 = Hb(Unsafe.Add(ref cp, 8), t132, Unsafe.Add(ref cp, 56), t119, cosBit);
        V t154 = Hb(Unsafe.Add(ref cp, 60), t138, Unsafe.Add(ref cp, 4), t145, cosBit);
        V t155 = Hb(Unsafe.Add(ref cp, 28), t139, Unsafe.Add(ref cp, 36), t144, cosBit);
        V t156 = Hb(Unsafe.Add(ref cp, 44), t140, Unsafe.Add(ref cp, 20), t143, cosBit);
        V t157 = Hb(Unsafe.Add(ref cp, 12), t141, Unsafe.Add(ref cp, 52), t142, cosBit);
        V t158 = Hb(Unsafe.Add(ref cp, 12), t142, -Unsafe.Add(ref cp, 52), t141, cosBit);
        V t159 = Hb(Unsafe.Add(ref cp, 44), t143, -Unsafe.Add(ref cp, 20), t140, cosBit);
        V t160 = Hb(Unsafe.Add(ref cp, 28), t144, -Unsafe.Add(ref cp, 36), t139, cosBit);
        V t161 = Hb(Unsafe.Add(ref cp, 60), t145, -Unsafe.Add(ref cp, 4), t138, cosBit);
        V t162 = t118 + t146;
        V t163 = -t146 + t118;
        V t164 = -t147 + t121;
        V t165 = t121 + t147;
        V t166 = t122 + t148;
        V t167 = -t148 + t122;
        V t168 = -t149 + t125;
        V t169 = t125 + t149;
        V t170 = t126 + t150;
        V t171 = -t150 + t126;
        V t172 = -t151 + t129;
        V t173 = t129 + t151;
        V t174 = t130 + t152;
        V t175 = -t152 + t130;
        V t176 = -t153 + t133;
        V t177 = t133 + t153;
        V t178 = Hb(Unsafe.Add(ref cp, 62), t162, Unsafe.Add(ref cp, 2), t177, cosBit);
        V t179 = Hb(Unsafe.Add(ref cp, 30), t163, Unsafe.Add(ref cp, 34), t176, cosBit);
        V t180 = Hb(Unsafe.Add(ref cp, 46), t164, Unsafe.Add(ref cp, 18), t175, cosBit);
        V t181 = Hb(Unsafe.Add(ref cp, 14), t165, Unsafe.Add(ref cp, 50), t174, cosBit);
        V t182 = Hb(Unsafe.Add(ref cp, 54), t166, Unsafe.Add(ref cp, 10), t173, cosBit);
        V t183 = Hb(Unsafe.Add(ref cp, 22), t167, Unsafe.Add(ref cp, 42), t172, cosBit);
        V t184 = Hb(Unsafe.Add(ref cp, 38), t168, Unsafe.Add(ref cp, 26), t171, cosBit);
        V t185 = Hb(Unsafe.Add(ref cp, 6), t169, Unsafe.Add(ref cp, 58), t170, cosBit);
        V t186 = Hb(Unsafe.Add(ref cp, 6), t170, -Unsafe.Add(ref cp, 58), t169, cosBit);
        V t187 = Hb(Unsafe.Add(ref cp, 38), t171, -Unsafe.Add(ref cp, 26), t168, cosBit);
        V t188 = Hb(Unsafe.Add(ref cp, 22), t172, -Unsafe.Add(ref cp, 42), t167, cosBit);
        V t189 = Hb(Unsafe.Add(ref cp, 54), t173, -Unsafe.Add(ref cp, 10), t166, cosBit);
        V t190 = Hb(Unsafe.Add(ref cp, 14), t174, -Unsafe.Add(ref cp, 50), t165, cosBit);
        V t191 = Hb(Unsafe.Add(ref cp, 46), t175, -Unsafe.Add(ref cp, 18), t164, cosBit);
        V t192 = Hb(Unsafe.Add(ref cp, 30), t176, -Unsafe.Add(ref cp, 34), t163, cosBit);
        V t193 = Hb(Unsafe.Add(ref cp, 62), t177, -Unsafe.Add(ref cp, 2), t162, cosBit);
        Unsafe.Add(ref output, 0) = t106;
        Unsafe.Add(ref output, 1) = t178;
        Unsafe.Add(ref output, 2) = t154;
        Unsafe.Add(ref output, 3) = t186;
        Unsafe.Add(ref output, 4) = t134;
        Unsafe.Add(ref output, 5) = t182;
        Unsafe.Add(ref output, 6) = t158;
        Unsafe.Add(ref output, 7) = t190;
        Unsafe.Add(ref output, 8) = t108;
        Unsafe.Add(ref output, 9) = t180;
        Unsafe.Add(ref output, 10) = t156;
        Unsafe.Add(ref output, 11) = t188;
        Unsafe.Add(ref output, 12) = t136;
        Unsafe.Add(ref output, 13) = t184;
        Unsafe.Add(ref output, 14) = t160;
        Unsafe.Add(ref output, 15) = t192;
        Unsafe.Add(ref output, 16) = t107;
        Unsafe.Add(ref output, 17) = t179;
        Unsafe.Add(ref output, 18) = t155;
        Unsafe.Add(ref output, 19) = t187;
        Unsafe.Add(ref output, 20) = t135;
        Unsafe.Add(ref output, 21) = t183;
        Unsafe.Add(ref output, 22) = t159;
        Unsafe.Add(ref output, 23) = t191;
        Unsafe.Add(ref output, 24) = t109;
        Unsafe.Add(ref output, 25) = t181;
        Unsafe.Add(ref output, 26) = t157;
        Unsafe.Add(ref output, 27) = t189;
        Unsafe.Add(ref output, 28) = t137;
        Unsafe.Add(ref output, 29) = t185;
        Unsafe.Add(ref output, 30) = t161;
        Unsafe.Add(ref output, 31) = t193;
    }

    private static void Fdct64(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x63 = Unsafe.Add(ref input, 63);
        V t0 = x0 + x63;
        V x1 = Unsafe.Add(ref input, 1);
        V x62 = Unsafe.Add(ref input, 62);
        V t1 = x1 + x62;
        V x2 = Unsafe.Add(ref input, 2);
        V x61 = Unsafe.Add(ref input, 61);
        V t2 = x2 + x61;
        V x3 = Unsafe.Add(ref input, 3);
        V x60 = Unsafe.Add(ref input, 60);
        V t3 = x3 + x60;
        V x4 = Unsafe.Add(ref input, 4);
        V x59 = Unsafe.Add(ref input, 59);
        V t4 = x4 + x59;
        V x5 = Unsafe.Add(ref input, 5);
        V x58 = Unsafe.Add(ref input, 58);
        V t5 = x5 + x58;
        V x6 = Unsafe.Add(ref input, 6);
        V x57 = Unsafe.Add(ref input, 57);
        V t6 = x6 + x57;
        V x7 = Unsafe.Add(ref input, 7);
        V x56 = Unsafe.Add(ref input, 56);
        V t7 = x7 + x56;
        V x8 = Unsafe.Add(ref input, 8);
        V x55 = Unsafe.Add(ref input, 55);
        V t8 = x8 + x55;
        V x9 = Unsafe.Add(ref input, 9);
        V x54 = Unsafe.Add(ref input, 54);
        V t9 = x9 + x54;
        V x10 = Unsafe.Add(ref input, 10);
        V x53 = Unsafe.Add(ref input, 53);
        V t10 = x10 + x53;
        V x11 = Unsafe.Add(ref input, 11);
        V x52 = Unsafe.Add(ref input, 52);
        V t11 = x11 + x52;
        V x12 = Unsafe.Add(ref input, 12);
        V x51 = Unsafe.Add(ref input, 51);
        V t12 = x12 + x51;
        V x13 = Unsafe.Add(ref input, 13);
        V x50 = Unsafe.Add(ref input, 50);
        V t13 = x13 + x50;
        V x14 = Unsafe.Add(ref input, 14);
        V x49 = Unsafe.Add(ref input, 49);
        V t14 = x14 + x49;
        V x15 = Unsafe.Add(ref input, 15);
        V x48 = Unsafe.Add(ref input, 48);
        V t15 = x15 + x48;
        V x16 = Unsafe.Add(ref input, 16);
        V x47 = Unsafe.Add(ref input, 47);
        V t16 = x16 + x47;
        V x17 = Unsafe.Add(ref input, 17);
        V x46 = Unsafe.Add(ref input, 46);
        V t17 = x17 + x46;
        V x18 = Unsafe.Add(ref input, 18);
        V x45 = Unsafe.Add(ref input, 45);
        V t18 = x18 + x45;
        V x19 = Unsafe.Add(ref input, 19);
        V x44 = Unsafe.Add(ref input, 44);
        V t19 = x19 + x44;
        V x20 = Unsafe.Add(ref input, 20);
        V x43 = Unsafe.Add(ref input, 43);
        V t20 = x20 + x43;
        V x21 = Unsafe.Add(ref input, 21);
        V x42 = Unsafe.Add(ref input, 42);
        V t21 = x21 + x42;
        V x22 = Unsafe.Add(ref input, 22);
        V x41 = Unsafe.Add(ref input, 41);
        V t22 = x22 + x41;
        V x23 = Unsafe.Add(ref input, 23);
        V x40 = Unsafe.Add(ref input, 40);
        V t23 = x23 + x40;
        V x24 = Unsafe.Add(ref input, 24);
        V x39 = Unsafe.Add(ref input, 39);
        V t24 = x24 + x39;
        V x25 = Unsafe.Add(ref input, 25);
        V x38 = Unsafe.Add(ref input, 38);
        V t25 = x25 + x38;
        V x26 = Unsafe.Add(ref input, 26);
        V x37 = Unsafe.Add(ref input, 37);
        V t26 = x26 + x37;
        V x27 = Unsafe.Add(ref input, 27);
        V x36 = Unsafe.Add(ref input, 36);
        V t27 = x27 + x36;
        V x28 = Unsafe.Add(ref input, 28);
        V x35 = Unsafe.Add(ref input, 35);
        V t28 = x28 + x35;
        V x29 = Unsafe.Add(ref input, 29);
        V x34 = Unsafe.Add(ref input, 34);
        V t29 = x29 + x34;
        V x30 = Unsafe.Add(ref input, 30);
        V x33 = Unsafe.Add(ref input, 33);
        V t30 = x30 + x33;
        V x31 = Unsafe.Add(ref input, 31);
        V x32 = Unsafe.Add(ref input, 32);
        V t31 = x31 + x32;
        V t32 = -x32 + x31;
        V t33 = -x33 + x30;
        V t34 = -x34 + x29;
        V t35 = -x35 + x28;
        V t36 = -x36 + x27;
        V t37 = -x37 + x26;
        V t38 = -x38 + x25;
        V t39 = -x39 + x24;
        V t40 = -x40 + x23;
        V t41 = -x41 + x22;
        V t42 = -x42 + x21;
        V t43 = -x43 + x20;
        V t44 = -x44 + x19;
        V t45 = -x45 + x18;
        V t46 = -x46 + x17;
        V t47 = -x47 + x16;
        V t48 = -x48 + x15;
        V t49 = -x49 + x14;
        V t50 = -x50 + x13;
        V t51 = -x51 + x12;
        V t52 = -x52 + x11;
        V t53 = -x53 + x10;
        V t54 = -x54 + x9;
        V t55 = -x55 + x8;
        V t56 = -x56 + x7;
        V t57 = -x57 + x6;
        V t58 = -x58 + x5;
        V t59 = -x59 + x4;
        V t60 = -x60 + x3;
        V t61 = -x61 + x2;
        V t62 = -x62 + x1;
        V t63 = -x63 + x0;
        V t64 = t0 + t31;
        V t65 = t1 + t30;
        V t66 = t2 + t29;
        V t67 = t3 + t28;
        V t68 = t4 + t27;
        V t69 = t5 + t26;
        V t70 = t6 + t25;
        V t71 = t7 + t24;
        V t72 = t8 + t23;
        V t73 = t9 + t22;
        V t74 = t10 + t21;
        V t75 = t11 + t20;
        V t76 = t12 + t19;
        V t77 = t13 + t18;
        V t78 = t14 + t17;
        V t79 = t15 + t16;
        V t80 = -t16 + t15;
        V t81 = -t17 + t14;
        V t82 = -t18 + t13;
        V t83 = -t19 + t12;
        V t84 = -t20 + t11;
        V t85 = -t21 + t10;
        V t86 = -t22 + t9;
        V t87 = -t23 + t8;
        V t88 = -t24 + t7;
        V t89 = -t25 + t6;
        V t90 = -t26 + t5;
        V t91 = -t27 + t4;
        V t92 = -t28 + t3;
        V t93 = -t29 + t2;
        V t94 = -t30 + t1;
        V t95 = -t31 + t0;
        V t96 = Hb(-Unsafe.Add(ref cp, 32), t40, Unsafe.Add(ref cp, 32), t55, cosBit);
        V t97 = Hb(-Unsafe.Add(ref cp, 32), t41, Unsafe.Add(ref cp, 32), t54, cosBit);
        V t98 = Hb(-Unsafe.Add(ref cp, 32), t42, Unsafe.Add(ref cp, 32), t53, cosBit);
        V t99 = Hb(-Unsafe.Add(ref cp, 32), t43, Unsafe.Add(ref cp, 32), t52, cosBit);
        V t100 = Hb(-Unsafe.Add(ref cp, 32), t44, Unsafe.Add(ref cp, 32), t51, cosBit);
        V t101 = Hb(-Unsafe.Add(ref cp, 32), t45, Unsafe.Add(ref cp, 32), t50, cosBit);
        V t102 = Hb(-Unsafe.Add(ref cp, 32), t46, Unsafe.Add(ref cp, 32), t49, cosBit);
        V t103 = Hb(-Unsafe.Add(ref cp, 32), t47, Unsafe.Add(ref cp, 32), t48, cosBit);
        V t104 = Hb(Unsafe.Add(ref cp, 32), t48, Unsafe.Add(ref cp, 32), t47, cosBit);
        V t105 = Hb(Unsafe.Add(ref cp, 32), t49, Unsafe.Add(ref cp, 32), t46, cosBit);
        V t106 = Hb(Unsafe.Add(ref cp, 32), t50, Unsafe.Add(ref cp, 32), t45, cosBit);
        V t107 = Hb(Unsafe.Add(ref cp, 32), t51, Unsafe.Add(ref cp, 32), t44, cosBit);
        V t108 = Hb(Unsafe.Add(ref cp, 32), t52, Unsafe.Add(ref cp, 32), t43, cosBit);
        V t109 = Hb(Unsafe.Add(ref cp, 32), t53, Unsafe.Add(ref cp, 32), t42, cosBit);
        V t110 = Hb(Unsafe.Add(ref cp, 32), t54, Unsafe.Add(ref cp, 32), t41, cosBit);
        V t111 = Hb(Unsafe.Add(ref cp, 32), t55, Unsafe.Add(ref cp, 32), t40, cosBit);
        V t112 = t64 + t79;
        V t113 = t65 + t78;
        V t114 = t66 + t77;
        V t115 = t67 + t76;
        V t116 = t68 + t75;
        V t117 = t69 + t74;
        V t118 = t70 + t73;
        V t119 = t71 + t72;
        V t120 = -t72 + t71;
        V t121 = -t73 + t70;
        V t122 = -t74 + t69;
        V t123 = -t75 + t68;
        V t124 = -t76 + t67;
        V t125 = -t77 + t66;
        V t126 = -t78 + t65;
        V t127 = -t79 + t64;
        V t128 = Hb(-Unsafe.Add(ref cp, 32), t84, Unsafe.Add(ref cp, 32), t91, cosBit);
        V t129 = Hb(-Unsafe.Add(ref cp, 32), t85, Unsafe.Add(ref cp, 32), t90, cosBit);
        V t130 = Hb(-Unsafe.Add(ref cp, 32), t86, Unsafe.Add(ref cp, 32), t89, cosBit);
        V t131 = Hb(-Unsafe.Add(ref cp, 32), t87, Unsafe.Add(ref cp, 32), t88, cosBit);
        V t132 = Hb(Unsafe.Add(ref cp, 32), t88, Unsafe.Add(ref cp, 32), t87, cosBit);
        V t133 = Hb(Unsafe.Add(ref cp, 32), t89, Unsafe.Add(ref cp, 32), t86, cosBit);
        V t134 = Hb(Unsafe.Add(ref cp, 32), t90, Unsafe.Add(ref cp, 32), t85, cosBit);
        V t135 = Hb(Unsafe.Add(ref cp, 32), t91, Unsafe.Add(ref cp, 32), t84, cosBit);
        V t136 = t32 + t103;
        V t137 = t33 + t102;
        V t138 = t34 + t101;
        V t139 = t35 + t100;
        V t140 = t36 + t99;
        V t141 = t37 + t98;
        V t142 = t38 + t97;
        V t143 = t39 + t96;
        V t144 = -t96 + t39;
        V t145 = -t97 + t38;
        V t146 = -t98 + t37;
        V t147 = -t99 + t36;
        V t148 = -t100 + t35;
        V t149 = -t101 + t34;
        V t150 = -t102 + t33;
        V t151 = -t103 + t32;
        V t152 = -t104 + t63;
        V t153 = -t105 + t62;
        V t154 = -t106 + t61;
        V t155 = -t107 + t60;
        V t156 = -t108 + t59;
        V t157 = -t109 + t58;
        V t158 = -t110 + t57;
        V t159 = -t111 + t56;
        V t160 = t56 + t111;
        V t161 = t57 + t110;
        V t162 = t58 + t109;
        V t163 = t59 + t108;
        V t164 = t60 + t107;
        V t165 = t61 + t106;
        V t166 = t62 + t105;
        V t167 = t63 + t104;
        V t168 = t112 + t119;
        V t169 = t113 + t118;
        V t170 = t114 + t117;
        V t171 = t115 + t116;
        V t172 = -t116 + t115;
        V t173 = -t117 + t114;
        V t174 = -t118 + t113;
        V t175 = -t119 + t112;
        V t176 = Hb(-Unsafe.Add(ref cp, 32), t122, Unsafe.Add(ref cp, 32), t125, cosBit);
        V t177 = Hb(-Unsafe.Add(ref cp, 32), t123, Unsafe.Add(ref cp, 32), t124, cosBit);
        V t178 = Hb(Unsafe.Add(ref cp, 32), t124, Unsafe.Add(ref cp, 32), t123, cosBit);
        V t179 = Hb(Unsafe.Add(ref cp, 32), t125, Unsafe.Add(ref cp, 32), t122, cosBit);
        V t180 = t80 + t131;
        V t181 = t81 + t130;
        V t182 = t82 + t129;
        V t183 = t83 + t128;
        V t184 = -t128 + t83;
        V t185 = -t129 + t82;
        V t186 = -t130 + t81;
        V t187 = -t131 + t80;
        V t188 = -t132 + t95;
        V t189 = -t133 + t94;
        V t190 = -t134 + t93;
        V t191 = -t135 + t92;
        V t192 = t92 + t135;
        V t193 = t93 + t134;
        V t194 = t94 + t133;
        V t195 = t95 + t132;
        V t196 = Hb(-Unsafe.Add(ref cp, 16), t140, Unsafe.Add(ref cp, 48), t163, cosBit);
        V t197 = Hb(-Unsafe.Add(ref cp, 16), t141, Unsafe.Add(ref cp, 48), t162, cosBit);
        V t198 = Hb(-Unsafe.Add(ref cp, 16), t142, Unsafe.Add(ref cp, 48), t161, cosBit);
        V t199 = Hb(-Unsafe.Add(ref cp, 16), t143, Unsafe.Add(ref cp, 48), t160, cosBit);
        V t200 = Hb(-Unsafe.Add(ref cp, 48), t144, -Unsafe.Add(ref cp, 16), t159, cosBit);
        V t201 = Hb(-Unsafe.Add(ref cp, 48), t145, -Unsafe.Add(ref cp, 16), t158, cosBit);
        V t202 = Hb(-Unsafe.Add(ref cp, 48), t146, -Unsafe.Add(ref cp, 16), t157, cosBit);
        V t203 = Hb(-Unsafe.Add(ref cp, 48), t147, -Unsafe.Add(ref cp, 16), t156, cosBit);
        V t204 = Hb(Unsafe.Add(ref cp, 48), t156, -Unsafe.Add(ref cp, 16), t147, cosBit);
        V t205 = Hb(Unsafe.Add(ref cp, 48), t157, -Unsafe.Add(ref cp, 16), t146, cosBit);
        V t206 = Hb(Unsafe.Add(ref cp, 48), t158, -Unsafe.Add(ref cp, 16), t145, cosBit);
        V t207 = Hb(Unsafe.Add(ref cp, 48), t159, -Unsafe.Add(ref cp, 16), t144, cosBit);
        V t208 = Hb(Unsafe.Add(ref cp, 16), t160, Unsafe.Add(ref cp, 48), t143, cosBit);
        V t209 = Hb(Unsafe.Add(ref cp, 16), t161, Unsafe.Add(ref cp, 48), t142, cosBit);
        V t210 = Hb(Unsafe.Add(ref cp, 16), t162, Unsafe.Add(ref cp, 48), t141, cosBit);
        V t211 = Hb(Unsafe.Add(ref cp, 16), t163, Unsafe.Add(ref cp, 48), t140, cosBit);
        V t212 = t168 + t171;
        V t213 = t169 + t170;
        V t214 = -t170 + t169;
        V t215 = -t171 + t168;
        V t216 = Hb(-Unsafe.Add(ref cp, 32), t173, Unsafe.Add(ref cp, 32), t174, cosBit);
        V t217 = Hb(Unsafe.Add(ref cp, 32), t174, Unsafe.Add(ref cp, 32), t173, cosBit);
        V t218 = t120 + t177;
        V t219 = t121 + t176;
        V t220 = -t176 + t121;
        V t221 = -t177 + t120;
        V t222 = -t178 + t127;
        V t223 = -t179 + t126;
        V t224 = t126 + t179;
        V t225 = t127 + t178;
        V t226 = Hb(-Unsafe.Add(ref cp, 16), t182, Unsafe.Add(ref cp, 48), t193, cosBit);
        V t227 = Hb(-Unsafe.Add(ref cp, 16), t183, Unsafe.Add(ref cp, 48), t192, cosBit);
        V t228 = Hb(-Unsafe.Add(ref cp, 48), t184, -Unsafe.Add(ref cp, 16), t191, cosBit);
        V t229 = Hb(-Unsafe.Add(ref cp, 48), t185, -Unsafe.Add(ref cp, 16), t190, cosBit);
        V t230 = Hb(Unsafe.Add(ref cp, 48), t190, -Unsafe.Add(ref cp, 16), t185, cosBit);
        V t231 = Hb(Unsafe.Add(ref cp, 48), t191, -Unsafe.Add(ref cp, 16), t184, cosBit);
        V t232 = Hb(Unsafe.Add(ref cp, 16), t192, Unsafe.Add(ref cp, 48), t183, cosBit);
        V t233 = Hb(Unsafe.Add(ref cp, 16), t193, Unsafe.Add(ref cp, 48), t182, cosBit);
        V t234 = t136 + t199;
        V t235 = t137 + t198;
        V t236 = t138 + t197;
        V t237 = t139 + t196;
        V t238 = -t196 + t139;
        V t239 = -t197 + t138;
        V t240 = -t198 + t137;
        V t241 = -t199 + t136;
        V t242 = -t200 + t151;
        V t243 = -t201 + t150;
        V t244 = -t202 + t149;
        V t245 = -t203 + t148;
        V t246 = t148 + t203;
        V t247 = t149 + t202;
        V t248 = t150 + t201;
        V t249 = t151 + t200;
        V t250 = t152 + t207;
        V t251 = t153 + t206;
        V t252 = t154 + t205;
        V t253 = t155 + t204;
        V t254 = -t204 + t155;
        V t255 = -t205 + t154;
        V t256 = -t206 + t153;
        V t257 = -t207 + t152;
        V t258 = -t208 + t167;
        V t259 = -t209 + t166;
        V t260 = -t210 + t165;
        V t261 = -t211 + t164;
        V t262 = t164 + t211;
        V t263 = t165 + t210;
        V t264 = t166 + t209;
        V t265 = t167 + t208;
        V t266 = Hb(Unsafe.Add(ref cp, 32), t212, Unsafe.Add(ref cp, 32), t213, cosBit);
        V t267 = Hb(-Unsafe.Add(ref cp, 32), t213, Unsafe.Add(ref cp, 32), t212, cosBit);
        V t268 = Hb(Unsafe.Add(ref cp, 48), t214, Unsafe.Add(ref cp, 16), t215, cosBit);
        V t269 = Hb(Unsafe.Add(ref cp, 48), t215, -Unsafe.Add(ref cp, 16), t214, cosBit);
        V t270 = t172 + t216;
        V t271 = -t216 + t172;
        V t272 = -t217 + t175;
        V t273 = t175 + t217;
        V t274 = Hb(-Unsafe.Add(ref cp, 16), t219, Unsafe.Add(ref cp, 48), t224, cosBit);
        V t275 = Hb(-Unsafe.Add(ref cp, 48), t220, -Unsafe.Add(ref cp, 16), t223, cosBit);
        V t276 = Hb(Unsafe.Add(ref cp, 48), t223, -Unsafe.Add(ref cp, 16), t220, cosBit);
        V t277 = Hb(Unsafe.Add(ref cp, 16), t224, Unsafe.Add(ref cp, 48), t219, cosBit);
        V t278 = t180 + t227;
        V t279 = t181 + t226;
        V t280 = -t226 + t181;
        V t281 = -t227 + t180;
        V t282 = -t228 + t187;
        V t283 = -t229 + t186;
        V t284 = t186 + t229;
        V t285 = t187 + t228;
        V t286 = t188 + t231;
        V t287 = t189 + t230;
        V t288 = -t230 + t189;
        V t289 = -t231 + t188;
        V t290 = -t232 + t195;
        V t291 = -t233 + t194;
        V t292 = t194 + t233;
        V t293 = t195 + t232;
        V t294 = Hb(-Unsafe.Add(ref cp, 8), t236, Unsafe.Add(ref cp, 56), t263, cosBit);
        V t295 = Hb(-Unsafe.Add(ref cp, 8), t237, Unsafe.Add(ref cp, 56), t262, cosBit);
        V t296 = Hb(-Unsafe.Add(ref cp, 56), t238, -Unsafe.Add(ref cp, 8), t261, cosBit);
        V t297 = Hb(-Unsafe.Add(ref cp, 56), t239, -Unsafe.Add(ref cp, 8), t260, cosBit);
        V t298 = Hb(-Unsafe.Add(ref cp, 40), t244, Unsafe.Add(ref cp, 24), t255, cosBit);
        V t299 = Hb(-Unsafe.Add(ref cp, 40), t245, Unsafe.Add(ref cp, 24), t254, cosBit);
        V t300 = Hb(-Unsafe.Add(ref cp, 24), t246, -Unsafe.Add(ref cp, 40), t253, cosBit);
        V t301 = Hb(-Unsafe.Add(ref cp, 24), t247, -Unsafe.Add(ref cp, 40), t252, cosBit);
        V t302 = Hb(Unsafe.Add(ref cp, 24), t252, -Unsafe.Add(ref cp, 40), t247, cosBit);
        V t303 = Hb(Unsafe.Add(ref cp, 24), t253, -Unsafe.Add(ref cp, 40), t246, cosBit);
        V t304 = Hb(Unsafe.Add(ref cp, 40), t254, Unsafe.Add(ref cp, 24), t245, cosBit);
        V t305 = Hb(Unsafe.Add(ref cp, 40), t255, Unsafe.Add(ref cp, 24), t244, cosBit);
        V t306 = Hb(Unsafe.Add(ref cp, 56), t260, -Unsafe.Add(ref cp, 8), t239, cosBit);
        V t307 = Hb(Unsafe.Add(ref cp, 56), t261, -Unsafe.Add(ref cp, 8), t238, cosBit);
        V t308 = Hb(Unsafe.Add(ref cp, 8), t262, Unsafe.Add(ref cp, 56), t237, cosBit);
        V t309 = Hb(Unsafe.Add(ref cp, 8), t263, Unsafe.Add(ref cp, 56), t236, cosBit);
        V t310 = Hb(Unsafe.Add(ref cp, 56), t270, Unsafe.Add(ref cp, 8), t273, cosBit);
        V t311 = Hb(Unsafe.Add(ref cp, 24), t271, Unsafe.Add(ref cp, 40), t272, cosBit);
        V t312 = Hb(Unsafe.Add(ref cp, 24), t272, -Unsafe.Add(ref cp, 40), t271, cosBit);
        V t313 = Hb(Unsafe.Add(ref cp, 56), t273, -Unsafe.Add(ref cp, 8), t270, cosBit);
        V t314 = t218 + t274;
        V t315 = -t274 + t218;
        V t316 = -t275 + t221;
        V t317 = t221 + t275;
        V t318 = t222 + t276;
        V t319 = -t276 + t222;
        V t320 = -t277 + t225;
        V t321 = t225 + t277;
        V t322 = Hb(-Unsafe.Add(ref cp, 8), t279, Unsafe.Add(ref cp, 56), t292, cosBit);
        V t323 = Hb(-Unsafe.Add(ref cp, 56), t280, -Unsafe.Add(ref cp, 8), t291, cosBit);
        V t324 = Hb(-Unsafe.Add(ref cp, 40), t283, Unsafe.Add(ref cp, 24), t288, cosBit);
        V t325 = Hb(-Unsafe.Add(ref cp, 24), t284, -Unsafe.Add(ref cp, 40), t287, cosBit);
        V t326 = Hb(Unsafe.Add(ref cp, 24), t287, -Unsafe.Add(ref cp, 40), t284, cosBit);
        V t327 = Hb(Unsafe.Add(ref cp, 40), t288, Unsafe.Add(ref cp, 24), t283, cosBit);
        V t328 = Hb(Unsafe.Add(ref cp, 56), t291, -Unsafe.Add(ref cp, 8), t280, cosBit);
        V t329 = Hb(Unsafe.Add(ref cp, 8), t292, Unsafe.Add(ref cp, 56), t279, cosBit);
        V t330 = t234 + t295;
        V t331 = t235 + t294;
        V t332 = -t294 + t235;
        V t333 = -t295 + t234;
        V t334 = -t296 + t241;
        V t335 = -t297 + t240;
        V t336 = t240 + t297;
        V t337 = t241 + t296;
        V t338 = t242 + t299;
        V t339 = t243 + t298;
        V t340 = -t298 + t243;
        V t341 = -t299 + t242;
        V t342 = -t300 + t249;
        V t343 = -t301 + t248;
        V t344 = t248 + t301;
        V t345 = t249 + t300;
        V t346 = t250 + t303;
        V t347 = t251 + t302;
        V t348 = -t302 + t251;
        V t349 = -t303 + t250;
        V t350 = -t304 + t257;
        V t351 = -t305 + t256;
        V t352 = t256 + t305;
        V t353 = t257 + t304;
        V t354 = t258 + t307;
        V t355 = t259 + t306;
        V t356 = -t306 + t259;
        V t357 = -t307 + t258;
        V t358 = -t308 + t265;
        V t359 = -t309 + t264;
        V t360 = t264 + t309;
        V t361 = t265 + t308;
        V t362 = Hb(Unsafe.Add(ref cp, 60), t314, Unsafe.Add(ref cp, 4), t321, cosBit);
        V t363 = Hb(Unsafe.Add(ref cp, 28), t315, Unsafe.Add(ref cp, 36), t320, cosBit);
        V t364 = Hb(Unsafe.Add(ref cp, 44), t316, Unsafe.Add(ref cp, 20), t319, cosBit);
        V t365 = Hb(Unsafe.Add(ref cp, 12), t317, Unsafe.Add(ref cp, 52), t318, cosBit);
        V t366 = Hb(Unsafe.Add(ref cp, 12), t318, -Unsafe.Add(ref cp, 52), t317, cosBit);
        V t367 = Hb(Unsafe.Add(ref cp, 44), t319, -Unsafe.Add(ref cp, 20), t316, cosBit);
        V t368 = Hb(Unsafe.Add(ref cp, 28), t320, -Unsafe.Add(ref cp, 36), t315, cosBit);
        V t369 = Hb(Unsafe.Add(ref cp, 60), t321, -Unsafe.Add(ref cp, 4), t314, cosBit);
        V t370 = t278 + t322;
        V t371 = -t322 + t278;
        V t372 = -t323 + t281;
        V t373 = t281 + t323;
        V t374 = t282 + t324;
        V t375 = -t324 + t282;
        V t376 = -t325 + t285;
        V t377 = t285 + t325;
        V t378 = t286 + t326;
        V t379 = -t326 + t286;
        V t380 = -t327 + t289;
        V t381 = t289 + t327;
        V t382 = t290 + t328;
        V t383 = -t328 + t290;
        V t384 = -t329 + t293;
        V t385 = t293 + t329;
        V t386 = Hb(-Unsafe.Add(ref cp, 4), t331, Unsafe.Add(ref cp, 60), t360, cosBit);
        V t387 = Hb(-Unsafe.Add(ref cp, 60), t332, -Unsafe.Add(ref cp, 4), t359, cosBit);
        V t388 = Hb(-Unsafe.Add(ref cp, 36), t335, Unsafe.Add(ref cp, 28), t356, cosBit);
        V t389 = Hb(-Unsafe.Add(ref cp, 28), t336, -Unsafe.Add(ref cp, 36), t355, cosBit);
        V t390 = Hb(-Unsafe.Add(ref cp, 20), t339, Unsafe.Add(ref cp, 44), t352, cosBit);
        V t391 = Hb(-Unsafe.Add(ref cp, 44), t340, -Unsafe.Add(ref cp, 20), t351, cosBit);
        V t392 = Hb(-Unsafe.Add(ref cp, 52), t343, Unsafe.Add(ref cp, 12), t348, cosBit);
        V t393 = Hb(-Unsafe.Add(ref cp, 12), t344, -Unsafe.Add(ref cp, 52), t347, cosBit);
        V t394 = Hb(Unsafe.Add(ref cp, 12), t347, -Unsafe.Add(ref cp, 52), t344, cosBit);
        V t395 = Hb(Unsafe.Add(ref cp, 52), t348, Unsafe.Add(ref cp, 12), t343, cosBit);
        V t396 = Hb(Unsafe.Add(ref cp, 44), t351, -Unsafe.Add(ref cp, 20), t340, cosBit);
        V t397 = Hb(Unsafe.Add(ref cp, 20), t352, Unsafe.Add(ref cp, 44), t339, cosBit);
        V t398 = Hb(Unsafe.Add(ref cp, 28), t355, -Unsafe.Add(ref cp, 36), t336, cosBit);
        V t399 = Hb(Unsafe.Add(ref cp, 36), t356, Unsafe.Add(ref cp, 28), t335, cosBit);
        V t400 = Hb(Unsafe.Add(ref cp, 60), t359, -Unsafe.Add(ref cp, 4), t332, cosBit);
        V t401 = Hb(Unsafe.Add(ref cp, 4), t360, Unsafe.Add(ref cp, 60), t331, cosBit);
        V t402 = Hb(Unsafe.Add(ref cp, 62), t370, Unsafe.Add(ref cp, 2), t385, cosBit);
        V t403 = Hb(Unsafe.Add(ref cp, 30), t371, Unsafe.Add(ref cp, 34), t384, cosBit);
        V t404 = Hb(Unsafe.Add(ref cp, 46), t372, Unsafe.Add(ref cp, 18), t383, cosBit);
        V t405 = Hb(Unsafe.Add(ref cp, 14), t373, Unsafe.Add(ref cp, 50), t382, cosBit);
        V t406 = Hb(Unsafe.Add(ref cp, 54), t374, Unsafe.Add(ref cp, 10), t381, cosBit);
        V t407 = Hb(Unsafe.Add(ref cp, 22), t375, Unsafe.Add(ref cp, 42), t380, cosBit);
        V t408 = Hb(Unsafe.Add(ref cp, 38), t376, Unsafe.Add(ref cp, 26), t379, cosBit);
        V t409 = Hb(Unsafe.Add(ref cp, 6), t377, Unsafe.Add(ref cp, 58), t378, cosBit);
        V t410 = Hb(Unsafe.Add(ref cp, 6), t378, -Unsafe.Add(ref cp, 58), t377, cosBit);
        V t411 = Hb(Unsafe.Add(ref cp, 38), t379, -Unsafe.Add(ref cp, 26), t376, cosBit);
        V t412 = Hb(Unsafe.Add(ref cp, 22), t380, -Unsafe.Add(ref cp, 42), t375, cosBit);
        V t413 = Hb(Unsafe.Add(ref cp, 54), t381, -Unsafe.Add(ref cp, 10), t374, cosBit);
        V t414 = Hb(Unsafe.Add(ref cp, 14), t382, -Unsafe.Add(ref cp, 50), t373, cosBit);
        V t415 = Hb(Unsafe.Add(ref cp, 46), t383, -Unsafe.Add(ref cp, 18), t372, cosBit);
        V t416 = Hb(Unsafe.Add(ref cp, 30), t384, -Unsafe.Add(ref cp, 34), t371, cosBit);
        V t417 = Hb(Unsafe.Add(ref cp, 62), t385, -Unsafe.Add(ref cp, 2), t370, cosBit);
        V t418 = t330 + t386;
        V t419 = -t386 + t330;
        V t420 = -t387 + t333;
        V t421 = t333 + t387;
        V t422 = t334 + t388;
        V t423 = -t388 + t334;
        V t424 = -t389 + t337;
        V t425 = t337 + t389;
        V t426 = t338 + t390;
        V t427 = -t390 + t338;
        V t428 = -t391 + t341;
        V t429 = t341 + t391;
        V t430 = t342 + t392;
        V t431 = -t392 + t342;
        V t432 = -t393 + t345;
        V t433 = t345 + t393;
        V t434 = t346 + t394;
        V t435 = -t394 + t346;
        V t436 = -t395 + t349;
        V t437 = t349 + t395;
        V t438 = t350 + t396;
        V t439 = -t396 + t350;
        V t440 = -t397 + t353;
        V t441 = t353 + t397;
        V t442 = t354 + t398;
        V t443 = -t398 + t354;
        V t444 = -t399 + t357;
        V t445 = t357 + t399;
        V t446 = t358 + t400;
        V t447 = -t400 + t358;
        V t448 = -t401 + t361;
        V t449 = t361 + t401;
        V t450 = Hb(Unsafe.Add(ref cp, 63), t418, Unsafe.Add(ref cp, 1), t449, cosBit);
        V t451 = Hb(Unsafe.Add(ref cp, 31), t419, Unsafe.Add(ref cp, 33), t448, cosBit);
        V t452 = Hb(Unsafe.Add(ref cp, 47), t420, Unsafe.Add(ref cp, 17), t447, cosBit);
        V t453 = Hb(Unsafe.Add(ref cp, 15), t421, Unsafe.Add(ref cp, 49), t446, cosBit);
        V t454 = Hb(Unsafe.Add(ref cp, 55), t422, Unsafe.Add(ref cp, 9), t445, cosBit);
        V t455 = Hb(Unsafe.Add(ref cp, 23), t423, Unsafe.Add(ref cp, 41), t444, cosBit);
        V t456 = Hb(Unsafe.Add(ref cp, 39), t424, Unsafe.Add(ref cp, 25), t443, cosBit);
        V t457 = Hb(Unsafe.Add(ref cp, 7), t425, Unsafe.Add(ref cp, 57), t442, cosBit);
        V t458 = Hb(Unsafe.Add(ref cp, 59), t426, Unsafe.Add(ref cp, 5), t441, cosBit);
        V t459 = Hb(Unsafe.Add(ref cp, 27), t427, Unsafe.Add(ref cp, 37), t440, cosBit);
        V t460 = Hb(Unsafe.Add(ref cp, 43), t428, Unsafe.Add(ref cp, 21), t439, cosBit);
        V t461 = Hb(Unsafe.Add(ref cp, 11), t429, Unsafe.Add(ref cp, 53), t438, cosBit);
        V t462 = Hb(Unsafe.Add(ref cp, 51), t430, Unsafe.Add(ref cp, 13), t437, cosBit);
        V t463 = Hb(Unsafe.Add(ref cp, 19), t431, Unsafe.Add(ref cp, 45), t436, cosBit);
        V t464 = Hb(Unsafe.Add(ref cp, 35), t432, Unsafe.Add(ref cp, 29), t435, cosBit);
        V t465 = Hb(Unsafe.Add(ref cp, 3), t433, Unsafe.Add(ref cp, 61), t434, cosBit);
        V t466 = Hb(Unsafe.Add(ref cp, 3), t434, -Unsafe.Add(ref cp, 61), t433, cosBit);
        V t467 = Hb(Unsafe.Add(ref cp, 35), t435, -Unsafe.Add(ref cp, 29), t432, cosBit);
        V t468 = Hb(Unsafe.Add(ref cp, 19), t436, -Unsafe.Add(ref cp, 45), t431, cosBit);
        V t469 = Hb(Unsafe.Add(ref cp, 51), t437, -Unsafe.Add(ref cp, 13), t430, cosBit);
        V t470 = Hb(Unsafe.Add(ref cp, 11), t438, -Unsafe.Add(ref cp, 53), t429, cosBit);
        V t471 = Hb(Unsafe.Add(ref cp, 43), t439, -Unsafe.Add(ref cp, 21), t428, cosBit);
        V t472 = Hb(Unsafe.Add(ref cp, 27), t440, -Unsafe.Add(ref cp, 37), t427, cosBit);
        V t473 = Hb(Unsafe.Add(ref cp, 59), t441, -Unsafe.Add(ref cp, 5), t426, cosBit);
        V t474 = Hb(Unsafe.Add(ref cp, 7), t442, -Unsafe.Add(ref cp, 57), t425, cosBit);
        V t475 = Hb(Unsafe.Add(ref cp, 39), t443, -Unsafe.Add(ref cp, 25), t424, cosBit);
        V t476 = Hb(Unsafe.Add(ref cp, 23), t444, -Unsafe.Add(ref cp, 41), t423, cosBit);
        V t477 = Hb(Unsafe.Add(ref cp, 55), t445, -Unsafe.Add(ref cp, 9), t422, cosBit);
        V t478 = Hb(Unsafe.Add(ref cp, 15), t446, -Unsafe.Add(ref cp, 49), t421, cosBit);
        V t479 = Hb(Unsafe.Add(ref cp, 47), t447, -Unsafe.Add(ref cp, 17), t420, cosBit);
        V t480 = Hb(Unsafe.Add(ref cp, 31), t448, -Unsafe.Add(ref cp, 33), t419, cosBit);
        V t481 = Hb(Unsafe.Add(ref cp, 63), t449, -Unsafe.Add(ref cp, 1), t418, cosBit);
        Unsafe.Add(ref output, 0) = t266;
        Unsafe.Add(ref output, 1) = t450;
        Unsafe.Add(ref output, 2) = t402;
        Unsafe.Add(ref output, 3) = t466;
        Unsafe.Add(ref output, 4) = t362;
        Unsafe.Add(ref output, 5) = t458;
        Unsafe.Add(ref output, 6) = t410;
        Unsafe.Add(ref output, 7) = t474;
        Unsafe.Add(ref output, 8) = t310;
        Unsafe.Add(ref output, 9) = t454;
        Unsafe.Add(ref output, 10) = t406;
        Unsafe.Add(ref output, 11) = t470;
        Unsafe.Add(ref output, 12) = t366;
        Unsafe.Add(ref output, 13) = t462;
        Unsafe.Add(ref output, 14) = t414;
        Unsafe.Add(ref output, 15) = t478;
        Unsafe.Add(ref output, 16) = t268;
        Unsafe.Add(ref output, 17) = t452;
        Unsafe.Add(ref output, 18) = t404;
        Unsafe.Add(ref output, 19) = t468;
        Unsafe.Add(ref output, 20) = t364;
        Unsafe.Add(ref output, 21) = t460;
        Unsafe.Add(ref output, 22) = t412;
        Unsafe.Add(ref output, 23) = t476;
        Unsafe.Add(ref output, 24) = t312;
        Unsafe.Add(ref output, 25) = t456;
        Unsafe.Add(ref output, 26) = t408;
        Unsafe.Add(ref output, 27) = t472;
        Unsafe.Add(ref output, 28) = t368;
        Unsafe.Add(ref output, 29) = t464;
        Unsafe.Add(ref output, 30) = t416;
        Unsafe.Add(ref output, 31) = t480;
        Unsafe.Add(ref output, 32) = t267;
        Unsafe.Add(ref output, 33) = t451;
        Unsafe.Add(ref output, 34) = t403;
        Unsafe.Add(ref output, 35) = t467;
        Unsafe.Add(ref output, 36) = t363;
        Unsafe.Add(ref output, 37) = t459;
        Unsafe.Add(ref output, 38) = t411;
        Unsafe.Add(ref output, 39) = t475;
        Unsafe.Add(ref output, 40) = t311;
        Unsafe.Add(ref output, 41) = t455;
        Unsafe.Add(ref output, 42) = t407;
        Unsafe.Add(ref output, 43) = t471;
        Unsafe.Add(ref output, 44) = t367;
        Unsafe.Add(ref output, 45) = t463;
        Unsafe.Add(ref output, 46) = t415;
        Unsafe.Add(ref output, 47) = t479;
        Unsafe.Add(ref output, 48) = t269;
        Unsafe.Add(ref output, 49) = t453;
        Unsafe.Add(ref output, 50) = t405;
        Unsafe.Add(ref output, 51) = t469;
        Unsafe.Add(ref output, 52) = t365;
        Unsafe.Add(ref output, 53) = t461;
        Unsafe.Add(ref output, 54) = t413;
        Unsafe.Add(ref output, 55) = t477;
        Unsafe.Add(ref output, 56) = t313;
        Unsafe.Add(ref output, 57) = t457;
        Unsafe.Add(ref output, 58) = t409;
        Unsafe.Add(ref output, 59) = t473;
        Unsafe.Add(ref output, 60) = t369;
        Unsafe.Add(ref output, 61) = t465;
        Unsafe.Add(ref output, 62) = t417;
        Unsafe.Add(ref output, 63) = t481;
    }

    private static void Fadst8(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x7 = Unsafe.Add(ref input, 7);
        V t0 = -x7;
        V x3 = Unsafe.Add(ref input, 3);
        V t1 = -x3;
        V x4 = Unsafe.Add(ref input, 4);
        V x1 = Unsafe.Add(ref input, 1);
        V t2 = -x1;
        V x6 = Unsafe.Add(ref input, 6);
        V x2 = Unsafe.Add(ref input, 2);
        V x5 = Unsafe.Add(ref input, 5);
        V t3 = -x5;
        V t4 = Hb(Unsafe.Add(ref cp, 32), t1, Unsafe.Add(ref cp, 32), x4, cosBit);
        V t5 = Hb(Unsafe.Add(ref cp, 32), t1, -Unsafe.Add(ref cp, 32), x4, cosBit);
        V t6 = Hb(Unsafe.Add(ref cp, 32), x2, Unsafe.Add(ref cp, 32), t3, cosBit);
        V t7 = Hb(Unsafe.Add(ref cp, 32), x2, -Unsafe.Add(ref cp, 32), t3, cosBit);
        V t8 = x0 + t4;
        V t9 = t0 + t5;
        V t10 = x0 - t4;
        V t11 = t0 - t5;
        V t12 = t2 + t6;
        V t13 = x6 + t7;
        V t14 = t2 - t6;
        V t15 = x6 - t7;
        V t16 = Hb(Unsafe.Add(ref cp, 16), t12, Unsafe.Add(ref cp, 48), t13, cosBit);
        V t17 = Hb(Unsafe.Add(ref cp, 48), t12, -Unsafe.Add(ref cp, 16), t13, cosBit);
        V t18 = Hb(-Unsafe.Add(ref cp, 48), t14, Unsafe.Add(ref cp, 16), t15, cosBit);
        V t19 = Hb(Unsafe.Add(ref cp, 16), t14, Unsafe.Add(ref cp, 48), t15, cosBit);
        V t20 = t8 + t16;
        V t21 = t9 + t17;
        V t22 = t10 + t18;
        V t23 = t11 + t19;
        V t24 = t8 - t16;
        V t25 = t9 - t17;
        V t26 = t10 - t18;
        V t27 = t11 - t19;
        V t28 = Hb(Unsafe.Add(ref cp, 4), t20, Unsafe.Add(ref cp, 60), t21, cosBit);
        V t29 = Hb(Unsafe.Add(ref cp, 60), t20, -Unsafe.Add(ref cp, 4), t21, cosBit);
        V t30 = Hb(Unsafe.Add(ref cp, 20), t22, Unsafe.Add(ref cp, 44), t23, cosBit);
        V t31 = Hb(Unsafe.Add(ref cp, 44), t22, -Unsafe.Add(ref cp, 20), t23, cosBit);
        V t32 = Hb(Unsafe.Add(ref cp, 36), t24, Unsafe.Add(ref cp, 28), t25, cosBit);
        V t33 = Hb(Unsafe.Add(ref cp, 28), t24, -Unsafe.Add(ref cp, 36), t25, cosBit);
        V t34 = Hb(Unsafe.Add(ref cp, 52), t26, Unsafe.Add(ref cp, 12), t27, cosBit);
        V t35 = Hb(Unsafe.Add(ref cp, 12), t26, -Unsafe.Add(ref cp, 52), t27, cosBit);
        Unsafe.Add(ref output, 0) = t29;
        Unsafe.Add(ref output, 1) = t34;
        Unsafe.Add(ref output, 2) = t31;
        Unsafe.Add(ref output, 3) = t32;
        Unsafe.Add(ref output, 4) = t33;
        Unsafe.Add(ref output, 5) = t30;
        Unsafe.Add(ref output, 6) = t35;
        Unsafe.Add(ref output, 7) = t28;
    }

    private static void Fadst16(ref V input, ref V output, int cosBit)
    {
        ref int cp = ref MemoryMarshal.GetArrayDataReference(CosPiData);
        cp = ref Unsafe.Add(ref cp, (cosBit - 10) * 64);
        V x0 = Unsafe.Add(ref input, 0);
        V x15 = Unsafe.Add(ref input, 15);
        V t0 = -x15;
        V x7 = Unsafe.Add(ref input, 7);
        V t1 = -x7;
        V x8 = Unsafe.Add(ref input, 8);
        V x3 = Unsafe.Add(ref input, 3);
        V t2 = -x3;
        V x12 = Unsafe.Add(ref input, 12);
        V x4 = Unsafe.Add(ref input, 4);
        V x11 = Unsafe.Add(ref input, 11);
        V t3 = -x11;
        V x1 = Unsafe.Add(ref input, 1);
        V t4 = -x1;
        V x14 = Unsafe.Add(ref input, 14);
        V x6 = Unsafe.Add(ref input, 6);
        V x9 = Unsafe.Add(ref input, 9);
        V t5 = -x9;
        V x2 = Unsafe.Add(ref input, 2);
        V x13 = Unsafe.Add(ref input, 13);
        V t6 = -x13;
        V x5 = Unsafe.Add(ref input, 5);
        V t7 = -x5;
        V x10 = Unsafe.Add(ref input, 10);
        V t8 = Hb(Unsafe.Add(ref cp, 32), t1, Unsafe.Add(ref cp, 32), x8, cosBit);
        V t9 = Hb(Unsafe.Add(ref cp, 32), t1, -Unsafe.Add(ref cp, 32), x8, cosBit);
        V t10 = Hb(Unsafe.Add(ref cp, 32), x4, Unsafe.Add(ref cp, 32), t3, cosBit);
        V t11 = Hb(Unsafe.Add(ref cp, 32), x4, -Unsafe.Add(ref cp, 32), t3, cosBit);
        V t12 = Hb(Unsafe.Add(ref cp, 32), x6, Unsafe.Add(ref cp, 32), t5, cosBit);
        V t13 = Hb(Unsafe.Add(ref cp, 32), x6, -Unsafe.Add(ref cp, 32), t5, cosBit);
        V t14 = Hb(Unsafe.Add(ref cp, 32), t7, Unsafe.Add(ref cp, 32), x10, cosBit);
        V t15 = Hb(Unsafe.Add(ref cp, 32), t7, -Unsafe.Add(ref cp, 32), x10, cosBit);
        V t16 = x0 + t8;
        V t17 = t0 + t9;
        V t18 = x0 - t8;
        V t19 = t0 - t9;
        V t20 = t2 + t10;
        V t21 = x12 + t11;
        V t22 = t2 - t10;
        V t23 = x12 - t11;
        V t24 = t4 + t12;
        V t25 = x14 + t13;
        V t26 = t4 - t12;
        V t27 = x14 - t13;
        V t28 = x2 + t14;
        V t29 = t6 + t15;
        V t30 = x2 - t14;
        V t31 = t6 - t15;
        V t32 = Hb(Unsafe.Add(ref cp, 16), t20, Unsafe.Add(ref cp, 48), t21, cosBit);
        V t33 = Hb(Unsafe.Add(ref cp, 48), t20, -Unsafe.Add(ref cp, 16), t21, cosBit);
        V t34 = Hb(-Unsafe.Add(ref cp, 48), t22, Unsafe.Add(ref cp, 16), t23, cosBit);
        V t35 = Hb(Unsafe.Add(ref cp, 16), t22, Unsafe.Add(ref cp, 48), t23, cosBit);
        V t36 = Hb(Unsafe.Add(ref cp, 16), t28, Unsafe.Add(ref cp, 48), t29, cosBit);
        V t37 = Hb(Unsafe.Add(ref cp, 48), t28, -Unsafe.Add(ref cp, 16), t29, cosBit);
        V t38 = Hb(-Unsafe.Add(ref cp, 48), t30, Unsafe.Add(ref cp, 16), t31, cosBit);
        V t39 = Hb(Unsafe.Add(ref cp, 16), t30, Unsafe.Add(ref cp, 48), t31, cosBit);
        V t40 = t16 + t32;
        V t41 = t17 + t33;
        V t42 = t18 + t34;
        V t43 = t19 + t35;
        V t44 = t16 - t32;
        V t45 = t17 - t33;
        V t46 = t18 - t34;
        V t47 = t19 - t35;
        V t48 = t24 + t36;
        V t49 = t25 + t37;
        V t50 = t26 + t38;
        V t51 = t27 + t39;
        V t52 = t24 - t36;
        V t53 = t25 - t37;
        V t54 = t26 - t38;
        V t55 = t27 - t39;
        V t56 = Hb(Unsafe.Add(ref cp, 8), t48, Unsafe.Add(ref cp, 56), t49, cosBit);
        V t57 = Hb(Unsafe.Add(ref cp, 56), t48, -Unsafe.Add(ref cp, 8), t49, cosBit);
        V t58 = Hb(Unsafe.Add(ref cp, 40), t50, Unsafe.Add(ref cp, 24), t51, cosBit);
        V t59 = Hb(Unsafe.Add(ref cp, 24), t50, -Unsafe.Add(ref cp, 40), t51, cosBit);
        V t60 = Hb(-Unsafe.Add(ref cp, 56), t52, Unsafe.Add(ref cp, 8), t53, cosBit);
        V t61 = Hb(Unsafe.Add(ref cp, 8), t52, Unsafe.Add(ref cp, 56), t53, cosBit);
        V t62 = Hb(-Unsafe.Add(ref cp, 24), t54, Unsafe.Add(ref cp, 40), t55, cosBit);
        V t63 = Hb(Unsafe.Add(ref cp, 40), t54, Unsafe.Add(ref cp, 24), t55, cosBit);
        V t64 = t40 + t56;
        V t65 = t41 + t57;
        V t66 = t42 + t58;
        V t67 = t43 + t59;
        V t68 = t44 + t60;
        V t69 = t45 + t61;
        V t70 = t46 + t62;
        V t71 = t47 + t63;
        V t72 = t40 - t56;
        V t73 = t41 - t57;
        V t74 = t42 - t58;
        V t75 = t43 - t59;
        V t76 = t44 - t60;
        V t77 = t45 - t61;
        V t78 = t46 - t62;
        V t79 = t47 - t63;
        V t80 = Hb(Unsafe.Add(ref cp, 2), t64, Unsafe.Add(ref cp, 62), t65, cosBit);
        V t81 = Hb(Unsafe.Add(ref cp, 62), t64, -Unsafe.Add(ref cp, 2), t65, cosBit);
        V t82 = Hb(Unsafe.Add(ref cp, 10), t66, Unsafe.Add(ref cp, 54), t67, cosBit);
        V t83 = Hb(Unsafe.Add(ref cp, 54), t66, -Unsafe.Add(ref cp, 10), t67, cosBit);
        V t84 = Hb(Unsafe.Add(ref cp, 18), t68, Unsafe.Add(ref cp, 46), t69, cosBit);
        V t85 = Hb(Unsafe.Add(ref cp, 46), t68, -Unsafe.Add(ref cp, 18), t69, cosBit);
        V t86 = Hb(Unsafe.Add(ref cp, 26), t70, Unsafe.Add(ref cp, 38), t71, cosBit);
        V t87 = Hb(Unsafe.Add(ref cp, 38), t70, -Unsafe.Add(ref cp, 26), t71, cosBit);
        V t88 = Hb(Unsafe.Add(ref cp, 34), t72, Unsafe.Add(ref cp, 30), t73, cosBit);
        V t89 = Hb(Unsafe.Add(ref cp, 30), t72, -Unsafe.Add(ref cp, 34), t73, cosBit);
        V t90 = Hb(Unsafe.Add(ref cp, 42), t74, Unsafe.Add(ref cp, 22), t75, cosBit);
        V t91 = Hb(Unsafe.Add(ref cp, 22), t74, -Unsafe.Add(ref cp, 42), t75, cosBit);
        V t92 = Hb(Unsafe.Add(ref cp, 50), t76, Unsafe.Add(ref cp, 14), t77, cosBit);
        V t93 = Hb(Unsafe.Add(ref cp, 14), t76, -Unsafe.Add(ref cp, 50), t77, cosBit);
        V t94 = Hb(Unsafe.Add(ref cp, 58), t78, Unsafe.Add(ref cp, 6), t79, cosBit);
        V t95 = Hb(Unsafe.Add(ref cp, 6), t78, -Unsafe.Add(ref cp, 58), t79, cosBit);
        Unsafe.Add(ref output, 0) = t81;
        Unsafe.Add(ref output, 1) = t94;
        Unsafe.Add(ref output, 2) = t83;
        Unsafe.Add(ref output, 3) = t92;
        Unsafe.Add(ref output, 4) = t85;
        Unsafe.Add(ref output, 5) = t90;
        Unsafe.Add(ref output, 6) = t87;
        Unsafe.Add(ref output, 7) = t88;
        Unsafe.Add(ref output, 8) = t89;
        Unsafe.Add(ref output, 9) = t86;
        Unsafe.Add(ref output, 10) = t91;
        Unsafe.Add(ref output, 11) = t84;
        Unsafe.Add(ref output, 12) = t93;
        Unsafe.Add(ref output, 13) = t82;
        Unsafe.Add(ref output, 14) = t95;
        Unsafe.Add(ref output, 15) = t80;
    }

    private static void Fadst4(ref V input, ref V output, int cosBit)
    {
        var sinpi = SinPi(cosBit);
        V x0 = input, x1 = Unsafe.Add(ref input, 1), x2 = Unsafe.Add(ref input, 2), x3 = Unsafe.Add(ref input, 3);
        V s0 = Vector256.Create(sinpi[1]) * x0, s1 = Vector256.Create(sinpi[4]) * x0;
        V s2 = Vector256.Create(sinpi[2]) * x1, s3 = Vector256.Create(sinpi[1]) * x1;
        V s4 = Vector256.Create(sinpi[3]) * x2, s5 = Vector256.Create(sinpi[4]) * x3, s6 = Vector256.Create(sinpi[2]) * x3;
        V s7 = x0 + x1;
        s7 = s7 - x3;
        x0 = s0 + s2; x1 = Vector256.Create(sinpi[3]) * s7; x2 = s1 - s3; x3 = s4;
        x0 = x0 + s5; x2 = x2 + s6;
        s0 = x0 + x3; s1 = x1; s2 = x2 - x3; s3 = x2 - x0;
        s3 = s3 + x3;
        var rnd = Vector256.Create(1 << (cosBit - 1));
        output = Vector256.ShiftRightArithmetic(s0 + rnd, cosBit);
        Unsafe.Add(ref output, 1) = Vector256.ShiftRightArithmetic(s1 + rnd, cosBit);
        Unsafe.Add(ref output, 2) = Vector256.ShiftRightArithmetic(s2 + rnd, cosBit);
        Unsafe.Add(ref output, 3) = Vector256.ShiftRightArithmetic(s3 + rnd, cosBit);
    }

    private static void Fidentity(ref V input, ref V output, int n)
    {
        for (int i = 0; i < n; i++)
        {
            V x = Unsafe.Add(ref input, i);
            Unsafe.Add(ref output, i) = n switch
            {
                4 => MulRound(x, 5793, 12),                 // x * NewSqrt2
                8 => x + x,                                 // x * 2
                16 => MulRound(x, 2 * 5793, 12),            // x * 2 * NewSqrt2
                _ => Vector256.ShiftLeft(x, 2),             // x * 4
            };
        }
    }

    // 1D kinds as Av1InvTransform.Type1dDct / Type1dAdst / Type1dIdentity
    private static void Txfm1d(int kind, int n, ref V input, ref V output, int cosBit)
    {
        if (kind == Av1InvTransform.Type1dIdentity) { Fidentity(ref input, ref output, n); return; }
        if (kind == Av1InvTransform.Type1dAdst)
        {
            if (n == 4) Fadst4(ref input, ref output, cosBit); else if (n == 8) Fadst8(ref input, ref output, cosBit); else Fadst16(ref input, ref output, cosBit);
            return;
        }
        switch (n)
        {
            case 4: Fdct4(ref input, ref output, cosBit); break;
            case 8: Fdct8(ref input, ref output, cosBit); break;
            case 16: Fdct16(ref input, ref output, cosBit); break;
            case 32: Fdct32(ref input, ref output, cosBit); break;
            default: Fdct64(ref input, ref output, cosBit); break;
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Transpose8Scalar(ref V r)
    {
        ref int m = ref Unsafe.As<V, int>(ref r);
        for (int i = 0; i < 8; i++)
            for (int j = i + 1; j < 8; j++)
            {
                int t = Unsafe.Add(ref m, i * 8 + j);
                Unsafe.Add(ref m, i * 8 + j) = Unsafe.Add(ref m, j * 8 + i);
                Unsafe.Add(ref m, j * 8 + i) = t;
            }
    }

    // av1_fwd_txfm_shift_ls / av1_fwd_cos_bit_col / _row (tx size order = Av1TxSize)
    private static readonly sbyte[] Shift = { 2, 0, 0, 2, -1, 0, 2, -2, 0, 2, -4, 0, 0, -2, -2, 2, -1, 0, 2, -1, 0, 2, -2, 0, 2, -2, 0,
        2, -4, 0, 2, -4, 0, 0, -2, -2, 2, -4, -2, 2, -1, 0, 2, -1, 0, 2, -2, 0, 2, -2, 0, 0, -2, 0, 2, -4, 0 };
    private static readonly sbyte[] CosBitCol = { 13, 13, 13, 0, 0, 13, 13, 13, 12, 0, 13, 13, 13, 12, 13, 0, 13, 13, 12, 13, 0, 0, 13, 12, 13 };
    private static readonly sbyte[] CosBitRow = { 13, 13, 12, 0, 0, 13, 13, 13, 12, 0, 13, 13, 12, 13, 12, 0, 12, 13, 12, 11, 0, 0, 12, 11, 10 };

    // 8 x 8 transpose of the 32-bit lanes of r0..r7 (in place)
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void Transpose8(ref V r)
    {
        if (!Avx2.IsSupported) { Transpose8Scalar(ref r); return; }
        V a0 = r, a1 = Unsafe.Add(ref r, 1), a2 = Unsafe.Add(ref r, 2), a3 = Unsafe.Add(ref r, 3);
        V a4 = Unsafe.Add(ref r, 4), a5 = Unsafe.Add(ref r, 5), a6 = Unsafe.Add(ref r, 6), a7 = Unsafe.Add(ref r, 7);
        V t0 = Avx2.UnpackLow(a0, a1), t1 = Avx2.UnpackHigh(a0, a1), t2 = Avx2.UnpackLow(a2, a3), t3 = Avx2.UnpackHigh(a2, a3);
        V t4 = Avx2.UnpackLow(a4, a5), t5 = Avx2.UnpackHigh(a4, a5), t6 = Avx2.UnpackLow(a6, a7), t7 = Avx2.UnpackHigh(a6, a7);
        V u0 = Avx2.UnpackLow(t0.AsInt64(), t2.AsInt64()).AsInt32(), u1 = Avx2.UnpackHigh(t0.AsInt64(), t2.AsInt64()).AsInt32();
        V u2 = Avx2.UnpackLow(t1.AsInt64(), t3.AsInt64()).AsInt32(), u3 = Avx2.UnpackHigh(t1.AsInt64(), t3.AsInt64()).AsInt32();
        V u4 = Avx2.UnpackLow(t4.AsInt64(), t6.AsInt64()).AsInt32(), u5 = Avx2.UnpackHigh(t4.AsInt64(), t6.AsInt64()).AsInt32();
        V u6 = Avx2.UnpackLow(t5.AsInt64(), t7.AsInt64()).AsInt32(), u7 = Avx2.UnpackHigh(t5.AsInt64(), t7.AsInt64()).AsInt32();
        r = Avx2.Permute2x128(u0, u4, 0x20); Unsafe.Add(ref r, 1) = Avx2.Permute2x128(u1, u5, 0x20);
        Unsafe.Add(ref r, 2) = Avx2.Permute2x128(u2, u6, 0x20); Unsafe.Add(ref r, 3) = Avx2.Permute2x128(u3, u7, 0x20);
        Unsafe.Add(ref r, 4) = Avx2.Permute2x128(u0, u4, 0x31); Unsafe.Add(ref r, 5) = Avx2.Permute2x128(u1, u5, 0x31);
        Unsafe.Add(ref r, 6) = Avx2.Permute2x128(u2, u6, 0x31); Unsafe.Add(ref r, 7) = Avx2.Permute2x128(u3, u7, 0x31);
    }

    /// <summary>libaom's forward transform of a w x h residual (row-major, stride w) with 1D kinds hKind (rows) / vKind
    /// (columns), quantised as libaom's quantiser sees it: qf = c * 2^tx_scale / dq (dc for rc 0), level = |qf| + 0.5 - bias
    /// floored (0 below 1), in the decoder's layout rc = ky + kx * min(h, 32) (the retained 32 x 32 of 64-point axes).</summary>
    // inverse scans (position -> scan index) per tx size, for the eob
    private static readonly int[]?[] InvScans = new int[]?[19];
    private static int[] InvScan(int tx)
    {
        var a = InvScans[tx];
        if (a != null) return a;
        var scan = Av1Tables.Scans[tx];
        a = new int[scan.Length];
        for (int i = 0; i < scan.Length; i++) a[scan[i]] = i;
        return InvScans[tx] = a;
    }

    // (ForwardQuant returns the eob: the scan index of the last nonzero level, -1 when all are zero)
    [SkipLocalsInit]
    internal static int ForwardQuant(ReadOnlySpan<int> residual, int w, int h, int txSize, int hKind, int vKind,
        double dcDq, double acDq, double bias, int[] levels, double[]? qfOut)
    {
        if (Lowbd && LowbdOn && w is 16 or 32 && h is 16 or 32) return ForwardQuantLbd(residual, w, h, txSize, hKind, vKind, dcDq, acDq, bias, levels, qfOut);
        ref int inv0 = ref MemoryMarshal.GetArrayDataReference(InvScan(txSize));
        var eobV = Vector128.Create(-1);   // per lane: the largest scan index of a nonzero level seen
        int lw = System.Numerics.BitOperations.Log2((uint)w) - 2, lh = System.Numerics.BitOperations.Log2((uint)h) - 2;
        int sh0 = Shift[txSize * 3], sh1 = -Shift[txSize * 3 + 1], sh2 = -Shift[txSize * 3 + 2];
        int cosCol = CosBitCol[lw * 5 + lh], cosRow = CosBitRow[lw * 5 + lh];
        bool rect2 = w == 2 * h || h == 2 * w;
        int sw = Math.Min(w, 32), sh = Math.Min(h, 32), ng = (w + 7) >> 3;
        int pels = w * h;
        double scale = 1 << ((pels > 256 ? 1 : 0) + (pels > 1024 ? 1 : 0));
        // column pass: group g holds columns 8g..8g+7 as lanes, one vector per row (rows past h stay zero for 4-tall)
        int hp = Math.Max(h, 8);
        Span<V> colS = stackalloc V[ng * hp + 64];
        ref V col = ref MemoryMarshal.GetReference(colS);
        ref V tmp = ref Unsafe.Add(ref col, ng * hp);           // 64 vectors of scratch
        ref int res0 = ref MemoryMarshal.GetReference(residual);
        var rnd1 = Vector256.Create(sh1 > 0 ? 1 << (sh1 - 1) : 0);
        for (int g = 0; g < ng; g++)
        {
            ref V cg = ref Unsafe.Add(ref col, g * hp);
            for (int r = 0; r < h; r++)
            {
                ref int p = ref Unsafe.Add(ref res0, r * w + g * 8);
                V v = w >= 8 ? Vector256.LoadUnsafe(ref p) : Vector256.Create(Vector128.LoadUnsafe(ref p), Vector128<int>.Zero);
                Unsafe.Add(ref tmp, r) = Vector256.ShiftLeft(v, sh0);
            }
            Txfm1d(vKind, h, ref tmp, ref cg, cosCol);
            for (int r = 0; r < h; r++)
            {
                ref V o = ref Unsafe.Add(ref cg, r);
                if (sh1 > 0) o = Vector256.ShiftRightArithmetic(o + rnd1, sh1);
            }
            for (int r = h; r < hp; r++) Unsafe.Add(ref cg, r) = V.Zero;
        }
        // row pass, 8 rows at a time (rows past 32 of a 64-tall block are discarded, so not transformed)
        Span<V> rinS = stackalloc V[64];
        ref V rin = ref MemoryMarshal.GetReference(rinS);
        var rnd2 = Vector256.Create(sh2 > 0 ? 1 << (sh2 - 1) : 0);
        var vdc = Vector256.Create(scale / dcDq, scale / acDq, scale / acDq, scale / acDq); var vac = Vector256.Create(scale / acDq);
        var half = Vector256.Create(0.5); var vbias = Vector256.Create(bias);
        var m1 = Vector128.Create(-1);
        ref int lv0 = ref MemoryArrayRef(levels);
        for (int r0 = 0; r0 < sh; r0 += 8)
        {
            for (int g = 0; g < ng; g++)
            {
                // rows r0..r0+7 of column group g, transposed: rin[8g + j] = column 8g + j, lanes = rows
                ref V src = ref Unsafe.Add(ref col, g * hp + r0);
                ref V dst = ref Unsafe.Add(ref rin, g * 8);
                for (int j = 0; j < 8; j++) Unsafe.Add(ref dst, j) = Unsafe.Add(ref src, j);
                Transpose8(ref dst);
            }
            Txfm1d(hKind, w, ref rin, ref tmp, cosRow);
            int nr = Math.Min(8, h - r0);
            for (int c = 0; c < sw; c++)
            {
                V v = Unsafe.Add(ref tmp, c);
                if (sh2 > 0) v = Vector256.ShiftRightArithmetic(v + rnd2, sh2);
                if (rect2) v = MulRound(v, 5793, 12);
                int rc = c * sh + r0;
                var q = Quant4(v.GetLower(), rc == 0 ? vdc : vac, half, vbias, ref Unsafe.Add(ref lv0, rc), qfOut, rc);
                eobV = Vector128.Max(eobV, Vector128.ConditionalSelect(Vector128.Equals(q, Vector128<int>.Zero), m1, Vector128.LoadUnsafe(ref inv0, (nuint)rc)));
                if (nr == 8)
                {
                    q = Quant4(v.GetUpper(), vac, half, vbias, ref Unsafe.Add(ref lv0, rc + 4), qfOut, rc + 4);
                    eobV = Vector128.Max(eobV, Vector128.ConditionalSelect(Vector128.Equals(q, Vector128<int>.Zero), m1, Vector128.LoadUnsafe(ref inv0, (nuint)(rc + 4))));
                }
            }
        }
        return Math.Max(Math.Max(eobV.GetElement(0), eobV.GetElement(1)), Math.Max(eobV.GetElement(2), eobV.GetElement(3)));
    }

    private static ref int MemoryArrayRef(int[] a) => ref MemoryMarshal.GetArrayDataReference(a);

    // Quant4 lane by lane (cvttpd2dq: out-of-range magnitudes give int.MinValue; psignd)
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static Vector128<int> Quant4Scalar(Vector128<int> c, Vector256<double> mul, Vector256<double> half,
        Vector256<double> bias, ref int dst, double[]? qfOut, int at)
    {
        Unsafe.SkipInit(out Vector128<int> li);
        for (int i = 0; i < 4; i++)
        {
            int ci = c.GetElement(i);
            double qf = ci * mul.GetElement(i);
            if (qfOut != null) qfOut[at + i] = qf;
            double t = Math.Abs(qf) + half.GetElement(i) - bias.GetElement(i);
            int l = t >= 2147483648.0 || t <= -2147483649.0 || double.IsNaN(t) ? int.MinValue : (int)t;
            Unsafe.Add(ref Unsafe.As<Vector128<int>, int>(ref li), i) = ci < 0 ? -l : ci == 0 ? 0 : l;
        }
        li.StoreUnsafe(ref dst);
        return li;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    // level = sign(c) * floor(|qf| + 0.5 - bias), 0 when that is below 1: the magnitude is truncated (the floor for it >= 0,
    // and 0 for it in (-1, 1), so any bias below 1.5) and the coefficient's sign applied in integers
    private static Vector128<int> Quant4(Vector128<int> c, Vector256<double> mul, Vector256<double> half,
        Vector256<double> bias, ref int dst, double[]? qfOut, int at)
    {
        if (!Avx.IsSupported) return Quant4Scalar(c, mul, half, bias, ref dst, qfOut, at);
        var qf = Avx.ConvertToVector256Double(c) * mul;   // c * 2^tx_scale / dq
        if (qfOut != null) qf.StoreUnsafe(ref MemoryMarshal.GetArrayDataReference(qfOut), (nuint)at);
        var li = Ssse3.Sign(Avx.ConvertToVector128Int32WithTruncation(Vector256.Abs(qf) + half - bias), c);
        li.StoreUnsafe(ref dst);
        return li;
    }
}
